import type { Difficulty } from "@/lib/puzzle/types";

export const PROMPT_6_REVIEW_DATE = "2026-07-25";

const categorySlugs: Record<string, string> = {
  animals: "animals-word-searches",
  "food-and-drink": "food-and-drink-word-searches",
  "nature-and-weather": "nature-and-weather-word-searches",
  science: "science-word-searches",
  geography: "geography-word-searches",
  "language-arts": "language-arts-word-searches",
  math: "math-word-searches",
  sports: "sports-word-searches",
  "classroom-values": "classroom-and-values-word-searches",
  holidays: "holiday-word-searches",
  history: "history-word-searches",
  travel: "travel-word-searches",
  music: "music-word-searches",
  "books-and-reading": "books-and-reading-word-searches",
  art: "art-word-searches"
};

const audiences: Record<string, string[]> = {
  animals: ["General", "classroom"],
  "food-and-drink": ["General", "families", "ESL"],
  "nature-and-weather": ["General", "classroom", "travel"],
  science: ["Classroom", "general"],
  geography: ["Classroom", "general"],
  "language-arts": ["Classroom", "language learners"],
  math: ["Classroom", "general"],
  sports: ["General", "classroom"],
  "classroom-values": ["Classroom", "families"],
  holidays: ["Families", "classroom"],
  history: ["Classroom", "general"],
  travel: ["General", "families", "travel"],
  music: ["General", "classroom"],
  "books-and-reading": ["Classroom", "general"],
  art: ["Classroom", "general"]
};

interface CuratedTopicPrompt6Source {
  order: number;
  title: string;
  categorySegment: string;
  slug: string;
  difficulty: Difficulty;
  words: string[];
  introduction: string;
  context: string;
}

const sourceTopics: CuratedTopicPrompt6Source[] = [
  {
    "order": 1,
    "title": "Wild Cats Word Search",
    "categorySegment": "animals",
    "slug": "wild-cats-word-search",
    "difficulty": "medium",
    "words": [
      "LION",
      "TIGER",
      "LEOPARD",
      "JAGUAR",
      "CHEETAH",
      "COUGAR",
      "LYNX",
      "BOBCAT",
      "OCELOT",
      "CARACAL",
      "SERVAL",
      "PANTHER",
      "MANE",
      "ROSETTES",
      "PREDATOR",
      "SAVANNA"
    ],
    "introduction": "Find wild cats from several habitats, including large cats, smaller forest hunters, and species adapted to open grasslands.",
    "context": "The word list combines familiar animals with features and habitat vocabulary, making it broader than a simple big-cat list."
  },
  {
    "order": 2,
    "title": "Dinosaurs Word Search",
    "categorySegment": "animals",
    "slug": "dinosaurs-word-search",
    "difficulty": "medium",
    "words": [
      "TYRANNOSAURUS",
      "TRICERATOPS",
      "STEGOSAURUS",
      "BRACHIOSAURUS",
      "VELOCIRAPTOR",
      "ANKYLOSAURUS",
      "DIPLODOCUS",
      "SPINOSAURUS",
      "FOSSIL",
      "JURASSIC",
      "CRETACEOUS",
      "HERBIVORE",
      "CARNIVORE",
      "EXTINCT",
      "PALEONTOLOGY",
      "REPTILE"
    ],
    "introduction": "Search for well-known dinosaurs together with vocabulary used to describe fossils, diets, and prehistoric periods.",
    "context": "The puzzle includes several dinosaur groups without relying on fictional characters, films, or branded dinosaur properties."
  },
  {
    "order": 3,
    "title": "Rainforest Animals Word Search",
    "categorySegment": "animals",
    "slug": "rainforest-animals-word-search",
    "difficulty": "medium",
    "words": [
      "JAGUAR",
      "TOUCAN",
      "SLOTH",
      "MACAW",
      "GORILLA",
      "ANACONDA",
      "TAPIR",
      "LEMUR",
      "CHAMELEON",
      "TREEFROG",
      "MONKEY",
      "PARROT",
      "OKAPI",
      "CAIMAN",
      "BUTTERFLY",
      "RAINFOREST"
    ],
    "introduction": "Find animals associated with tropical forests, from canopy birds and tree-dwelling mammals to reptiles and amphibians.",
    "context": "The list represents several rainforest regions without suggesting that every animal lives in the same forest."
  },
  {
    "order": 4,
    "title": "Arctic Animals Word Search",
    "categorySegment": "animals",
    "slug": "arctic-animals-word-search",
    "difficulty": "easy",
    "words": [
      "POLARBEAR",
      "SEAL",
      "WALRUS",
      "ARCTICFOX",
      "REINDEER",
      "NARWHAL",
      "PUFFIN",
      "HARE",
      "OWL",
      "WHALE",
      "TERN",
      "CARIBOU"
    ],
    "introduction": "Find animals associated with Arctic seas, tundra, coastal cliffs, and northern migration routes.",
    "context": "The forward-only puzzle uses recognizable cold-region animals and works well as an introductory polar theme."
  },
  {
    "order": 5,
    "title": "Desert Animals Word Search",
    "categorySegment": "animals",
    "slug": "desert-animals-word-search",
    "difficulty": "medium",
    "words": [
      "CAMEL",
      "FENNEC",
      "SCORPION",
      "RATTLESNAKE",
      "ROADRUNNER",
      "GECKO",
      "TORTOISE",
      "COYOTE",
      "JACKRABBIT",
      "LIZARD",
      "MEERKAT",
      "VULTURE",
      "IGUANA",
      "BEETLE",
      "ORYX",
      "DESERT"
    ],
    "introduction": "Search for mammals, reptiles, birds, and invertebrates adapted to dry desert environments.",
    "context": "The vocabulary spans several world deserts and focuses on general animal identification rather than one geographic region."
  },
  {
    "order": 6,
    "title": "Baby Animals Word Search",
    "categorySegment": "animals",
    "slug": "baby-animals-word-search",
    "difficulty": "easy",
    "words": [
      "PUPPY",
      "KITTEN",
      "CALF",
      "FOAL",
      "LAMB",
      "KID",
      "CHICK",
      "DUCKLING",
      "PIGLET",
      "CUB",
      "JOEY",
      "FAWN"
    ],
    "introduction": "Find the familiar names used for young pets, farm animals, birds, and wild mammals.",
    "context": "The compact grid supports introductory animal vocabulary and can be followed by matching each young animal to its adult name."
  },
  {
    "order": 7,
    "title": "Pizza Word Search",
    "categorySegment": "food-and-drink",
    "slug": "pizza-word-search",
    "difficulty": "easy",
    "words": [
      "PIZZA",
      "CHEESE",
      "SAUCE",
      "CRUST",
      "TOPPING",
      "SLICE",
      "OVEN",
      "DOUGH",
      "TOMATO",
      "PEPPER",
      "MUSHROOM",
      "OLIVE"
    ],
    "introduction": "Find pizza ingredients, preparation words, and familiar toppings in a compact grid.",
    "context": "The vocabulary remains generic and does not refer to restaurants, commercial products, or branded pizza styles."
  },
  {
    "order": 8,
    "title": "Pasta Word Search",
    "categorySegment": "food-and-drink",
    "slug": "pasta-word-search",
    "difficulty": "easy",
    "words": [
      "PASTA",
      "SPAGHETTI",
      "PENNE",
      "RAVIOLI",
      "LASAGNA",
      "NOODLES",
      "SAUCE",
      "CHEESE",
      "GARLIC",
      "BASIL",
      "TOMATO",
      "COLANDER"
    ],
    "introduction": "Search for pasta shapes, ingredients, sauces, and a common kitchen tool used when preparing pasta.",
    "context": "The puzzle offers recognizable cooking vocabulary without presenting a recipe or nutrition claim."
  },
  {
    "order": 9,
    "title": "Cooking Word Search",
    "categorySegment": "food-and-drink",
    "slug": "cooking-word-search",
    "difficulty": "medium",
    "words": [
      "COOKING",
      "CHOP",
      "SLICE",
      "STIR",
      "BOIL",
      "BAKE",
      "ROAST",
      "GRILL",
      "SIMMER",
      "SEASON",
      "RECIPE",
      "INGREDIENT",
      "SKILLET",
      "SAUCEPAN",
      "KITCHEN",
      "SERVE"
    ],
    "introduction": "Find common cooking actions, equipment, and planning words used when preparing a meal.",
    "context": "The list emphasizes practical kitchen vocabulary and works as a general cooking theme rather than a specific recipe."
  },
  {
    "order": 10,
    "title": "Kitchen Tools Word Search",
    "categorySegment": "food-and-drink",
    "slug": "kitchen-tools-word-search",
    "difficulty": "medium",
    "words": [
      "WHISK",
      "SPATULA",
      "TONGS",
      "LADLE",
      "GRATER",
      "PEELER",
      "COLANDER",
      "SKILLET",
      "SAUCEPAN",
      "CUTTINGBOARD",
      "MEASURINGCUP",
      "ROLLINGPIN",
      "MIXER",
      "BLENDER",
      "KNIFE",
      "OVENMITT"
    ],
    "introduction": "Search for tools used to mix, measure, cut, cook, and serve food.",
    "context": "The word bank covers hand tools, cookware, and small appliances commonly found in home kitchens."
  },
  {
    "order": 11,
    "title": "Candy Word Search",
    "categorySegment": "food-and-drink",
    "slug": "candy-word-search",
    "difficulty": "easy",
    "words": [
      "CANDY",
      "CHOCOLATE",
      "CARAMEL",
      "LOLLIPOP",
      "GUMDROP",
      "TAFFY",
      "FUDGE",
      "TOFFEE",
      "JELLYBEAN",
      "MINT",
      "LICORICE",
      "SPRINKLES"
    ],
    "introduction": "Find familiar candy types, flavors, and textures hidden in a forward-only grid.",
    "context": "The page uses generic confectionery vocabulary and avoids commercial brand names."
  },
  {
    "order": 12,
    "title": "Everyday Foods Word Search",
    "categorySegment": "food-and-drink",
    "slug": "everyday-foods-word-search",
    "difficulty": "easy",
    "words": [
      "BREAD",
      "RICE",
      "PASTA",
      "EGGS",
      "MILK",
      "CHEESE",
      "APPLE",
      "CARROT",
      "BEANS",
      "YOGURT",
      "CHICKEN",
      "OATMEAL"
    ],
    "introduction": "Search for familiar foods that appear in many kitchens, meals, and grocery lists.",
    "context": "The puzzle provides basic food vocabulary without classifying foods as medically healthy or unhealthy."
  },
  {
    "order": 13,
    "title": "Mountains Word Search",
    "categorySegment": "nature-and-weather",
    "slug": "mountains-word-search",
    "difficulty": "medium",
    "words": [
      "MOUNTAIN",
      "SUMMIT",
      "PEAK",
      "RIDGE",
      "VALLEY",
      "CLIFF",
      "GLACIER",
      "TRAIL",
      "SLOPE",
      "ALPINE",
      "FOOTHILL",
      "RANGE",
      "BOULDER",
      "ASCENT",
      "ELEVATION",
      "HORIZON"
    ],
    "introduction": "Find mountain landforms, trail vocabulary, and features visible across high-elevation landscapes.",
    "context": "The list includes both physical geography and general hiking terms without describing a specific mountain range."
  },
  {
    "order": 14,
    "title": "Rivers Word Search",
    "categorySegment": "nature-and-weather",
    "slug": "rivers-word-search",
    "difficulty": "medium",
    "words": [
      "RIVER",
      "STREAM",
      "CURRENT",
      "BANK",
      "CHANNEL",
      "SOURCE",
      "MOUTH",
      "TRIBUTARY",
      "DELTA",
      "RAPIDS",
      "WATERFALL",
      "WATERSHED",
      "FLOODPLAIN",
      "MEANDER",
      "BRIDGE",
      "ESTUARY"
    ],
    "introduction": "Search for river features, flowing-water vocabulary, and landforms created where rivers meet other bodies of water.",
    "context": "The words cover a river from its source through tributaries and channels to its mouth or delta."
  },
  {
    "order": 15,
    "title": "Wetlands Word Search",
    "categorySegment": "nature-and-weather",
    "slug": "wetlands-word-search",
    "difficulty": "medium",
    "words": [
      "WETLAND",
      "MARSH",
      "SWAMP",
      "BOG",
      "FEN",
      "REEDS",
      "POND",
      "WATER",
      "MUDFLAT",
      "HABITAT",
      "MIGRATION",
      "AMPHIBIAN",
      "WATERFOWL",
      "SEDGE",
      "FLOOD",
      "CONSERVATION"
    ],
    "introduction": "Find wetland types, plants, wildlife groups, and environmental features associated with waterlogged habitats.",
    "context": "The vocabulary distinguishes several wetland forms while keeping the puzzle suitable for general nature study."
  },
  {
    "order": 16,
    "title": "Camping Word Search",
    "categorySegment": "nature-and-weather",
    "slug": "camping-word-search",
    "difficulty": "easy",
    "words": [
      "TENT",
      "CAMPFIRE",
      "TRAIL",
      "BACKPACK",
      "LANTERN",
      "SLEEPINGBAG",
      "MAP",
      "COMPASS",
      "CABIN",
      "HIKE",
      "FOREST",
      "MARSHMALLOW"
    ],
    "introduction": "Find common camping equipment, outdoor activities, and familiar campsite features.",
    "context": "The word list supports a general camping or road-trip activity without providing wilderness-safety instructions."
  },
  {
    "order": 17,
    "title": "Plants Word Search",
    "categorySegment": "nature-and-weather",
    "slug": "plants-word-search",
    "difficulty": "medium",
    "words": [
      "PLANT",
      "ROOT",
      "STEM",
      "LEAF",
      "FLOWER",
      "SEED",
      "SPROUT",
      "POLLEN",
      "SOIL",
      "SUNLIGHT",
      "WATER",
      "GROWTH",
      "CHLOROPHYLL",
      "GERMINATION",
      "PHOTOSYNTHESIS",
      "GARDEN"
    ],
    "introduction": "Search for plant structures, growing conditions, and processes involved in plant development.",
    "context": "The list combines visible plant parts with introductory science vocabulary used when discussing growth."
  },
  {
    "order": 18,
    "title": "Earth Day Word Search",
    "categorySegment": "nature-and-weather",
    "slug": "earth-day-word-search",
    "difficulty": "medium",
    "words": [
      "EARTH",
      "PLANET",
      "RECYCLE",
      "REUSE",
      "REDUCE",
      "COMPOST",
      "CONSERVE",
      "ENERGY",
      "WATER",
      "FOREST",
      "OCEAN",
      "HABITAT",
      "CLEANUP",
      "POLLUTION",
      "CLIMATE",
      "NATURE"
    ],
    "introduction": "Find environmental vocabulary commonly used in Earth Day activities and conservation discussions.",
    "context": "The puzzle focuses on general actions and natural systems without making political, scientific-outcome, or personal-impact guarantees."
  },
  {
    "order": 19,
    "title": "Human Body Word Search",
    "categorySegment": "science",
    "slug": "human-body-word-search",
    "difficulty": "medium",
    "words": [
      "BRAIN",
      "HEART",
      "LUNGS",
      "STOMACH",
      "MUSCLE",
      "BONE",
      "SKIN",
      "BLOOD",
      "NERVE",
      "SPINE",
      "LIVER",
      "KIDNEY",
      "JOINT",
      "TENDON",
      "ORGAN",
      "SKELETON"
    ],
    "introduction": "Find major organs, tissues, structures, and body-system vocabulary in an introductory anatomy puzzle.",
    "context": "The page is an educational vocabulary activity and must not provide medical advice, diagnosis, or health claims."
  },
  {
    "order": 20,
    "title": "Scientific Method Word Search",
    "categorySegment": "science",
    "slug": "scientific-method-word-search",
    "difficulty": "medium",
    "words": [
      "QUESTION",
      "RESEARCH",
      "HYPOTHESIS",
      "EXPERIMENT",
      "VARIABLE",
      "CONTROL",
      "OBSERVE",
      "MEASURE",
      "DATA",
      "RESULT",
      "ANALYZE",
      "CONCLUSION",
      "REPEAT",
      "EVIDENCE",
      "PREDICT",
      "RECORD"
    ],
    "introduction": "Search for terms used when asking a question, planning an investigation, recording evidence, and evaluating results.",
    "context": "The vocabulary reflects a general investigation process and does not claim that every scientific field follows one rigid sequence."
  },
  {
    "order": 21,
    "title": "Lab Safety Word Search",
    "categorySegment": "science",
    "slug": "lab-safety-word-search",
    "difficulty": "easy",
    "words": [
      "GOGGLES",
      "GLOVES",
      "APRON",
      "LABEL",
      "CLEAN",
      "CAUTION",
      "WASH",
      "REPORT",
      "FOLLOW",
      "INSTRUCTIONS",
      "EQUIPMENT",
      "SUPERVISION"
    ],
    "introduction": "Find basic laboratory-safety vocabulary related to protective equipment, instructions, and reporting problems.",
    "context": "The puzzle is only a vocabulary review and must not replace teacher supervision, official procedures, or equipment-specific instructions."
  },
  {
    "order": 22,
    "title": "Electricity Word Search",
    "categorySegment": "science",
    "slug": "electricity-word-search",
    "difficulty": "medium",
    "words": [
      "ELECTRICITY",
      "CURRENT",
      "VOLTAGE",
      "CIRCUIT",
      "BATTERY",
      "WIRE",
      "SWITCH",
      "CONDUCTOR",
      "INSULATOR",
      "RESISTANCE",
      "CHARGE",
      "ELECTRON",
      "POWER",
      "ENERGY",
      "SERIES",
      "PARALLEL"
    ],
    "introduction": "Find introductory electricity vocabulary covering charge, circuits, current, voltage, and electrical materials.",
    "context": "The page supports terminology review and must not provide instructions for working with live electrical systems."
  },
  {
    "order": 23,
    "title": "Magnetism Word Search",
    "categorySegment": "science",
    "slug": "magnetism-word-search",
    "difficulty": "medium",
    "words": [
      "MAGNET",
      "NORTH",
      "SOUTH",
      "POLE",
      "ATTRACT",
      "REPEL",
      "FIELD",
      "COMPASS",
      "IRON",
      "STEEL",
      "FORCE",
      "CURRENT",
      "ELECTROMAGNET",
      "MAGNETIC",
      "CHARGE",
      "MOTION"
    ],
    "introduction": "Search for words describing magnetic poles, forces, fields, materials, and electromagnets.",
    "context": "The vocabulary connects common magnet observations with introductory physical-science terms."
  },
  {
    "order": 24,
    "title": "Earth Science Word Search",
    "categorySegment": "science",
    "slug": "earth-science-word-search",
    "difficulty": "hard",
    "words": [
      "ATMOSPHERE",
      "HYDROSPHERE",
      "GEOSPHERE",
      "BIOSPHERE",
      "WEATHERING",
      "EROSION",
      "DEPOSITION",
      "TECTONIC",
      "MINERAL",
      "ROCK",
      "FOSSIL",
      "VOLCANO",
      "EARTHQUAKE",
      "SEDIMENT",
      "CRUST",
      "MANTLE",
      "CORE",
      "CLIMATE",
      "WATERCYCLE",
      "CONTINENT"
    ],
    "introduction": "Find Earth-science vocabulary covering planetary systems, rocks, geological processes, climate, and tectonic activity.",
    "context": "The twenty-word list provides a broad review spanning several Earth-science units."
  },
  {
    "order": 25,
    "title": "Landforms Word Search",
    "categorySegment": "geography",
    "slug": "landforms-word-search",
    "difficulty": "medium",
    "words": [
      "MOUNTAIN",
      "VALLEY",
      "PLATEAU",
      "PLAIN",
      "CANYON",
      "ISLAND",
      "PENINSULA",
      "ISTHMUS",
      "DELTA",
      "DUNE",
      "CLIFF",
      "VOLCANO",
      "HILL",
      "BASIN",
      "CAVE",
      "GLACIER"
    ],
    "introduction": "Search for landforms created by elevation, water, erosion, deposition, and volcanic activity.",
    "context": "The list includes inland, coastal, and glacial features for a broad physical-geography review."
  },
  {
    "order": 26,
    "title": "Europe Word Search",
    "categorySegment": "geography",
    "slug": "europe-word-search",
    "difficulty": "hard",
    "words": [
      "FRANCE",
      "GERMANY",
      "ITALY",
      "SPAIN",
      "PORTUGAL",
      "IRELAND",
      "NORWAY",
      "SWEDEN",
      "FINLAND",
      "POLAND",
      "GREECE",
      "AUSTRIA",
      "BELGIUM",
      "CROATIA",
      "DENMARK",
      "HUNGARY",
      "ICELAND",
      "ROMANIA",
      "SERBIA",
      "UKRAINE"
    ],
    "introduction": "Find twenty European country names hidden across a larger grid.",
    "context": "The puzzle is a selected regional list rather than a claim to include every country or territory in Europe."
  },
  {
    "order": 27,
    "title": "Asia Word Search",
    "categorySegment": "geography",
    "slug": "asia-word-search",
    "difficulty": "hard",
    "words": [
      "CHINA",
      "INDIA",
      "JAPAN",
      "KOREA",
      "THAILAND",
      "VIETNAM",
      "MALAYSIA",
      "INDONESIA",
      "PHILIPPINES",
      "MONGOLIA",
      "NEPAL",
      "BHUTAN",
      "PAKISTAN",
      "BANGLADESH",
      "CAMBODIA",
      "SINGAPORE",
      "MYANMAR",
      "LAOS",
      "SRILANKA",
      "KAZAKHSTAN"
    ],
    "introduction": "Search for twenty countries and commonly used regional place names from across Asia.",
    "context": "The selection spans several parts of the continent and is not presented as a complete geopolitical list."
  },
  {
    "order": 28,
    "title": "Africa Word Search",
    "categorySegment": "geography",
    "slug": "africa-word-search",
    "difficulty": "hard",
    "words": [
      "EGYPT",
      "KENYA",
      "NIGERIA",
      "GHANA",
      "MOROCCO",
      "ALGERIA",
      "TUNISIA",
      "ETHIOPIA",
      "UGANDA",
      "RWANDA",
      "TANZANIA",
      "NAMIBIA",
      "BOTSWANA",
      "ZAMBIA",
      "ZIMBABWE",
      "SENEGAL",
      "ANGOLA",
      "MALAWI",
      "SOMALIA",
      "SUDAN"
    ],
    "introduction": "Find twenty African country names hidden horizontally, vertically, diagonally, forwards, and backwards.",
    "context": "The puzzle represents several African regions and does not imply that the selected countries form a complete list."
  },
  {
    "order": 29,
    "title": "North America Word Search",
    "categorySegment": "geography",
    "slug": "north-america-word-search",
    "difficulty": "hard",
    "words": [
      "CANADA",
      "MEXICO",
      "UNITEDSTATES",
      "GREENLAND",
      "GUATEMALA",
      "BELIZE",
      "HONDURAS",
      "NICARAGUA",
      "COSTARICA",
      "PANAMA",
      "CUBA",
      "JAMAICA",
      "HAITI",
      "BAHAMAS",
      "BARBADOS",
      "DOMINICA",
      "GRENADA",
      "TRINIDADTOBAGO",
      "ARCTIC",
      "CARIBBEAN"
    ],
    "introduction": "Search for countries, islands, and regional terms associated with North America and the Caribbean.",
    "context": "The word list mixes political geography with broad regional vocabulary and should not be described as an exhaustive country list."
  },
  {
    "order": 30,
    "title": "South America Word Search",
    "categorySegment": "geography",
    "slug": "south-america-word-search",
    "difficulty": "hard",
    "words": [
      "ARGENTINA",
      "BOLIVIA",
      "BRAZIL",
      "CHILE",
      "COLOMBIA",
      "ECUADOR",
      "GUYANA",
      "PARAGUAY",
      "PERU",
      "SURINAME",
      "URUGUAY",
      "VENEZUELA",
      "AMAZON",
      "ANDES",
      "PATAGONIA",
      "ATACAMA",
      "ORINOCO",
      "PAMPAS",
      "FRENCHGUIANA",
      "GALAPAGOS"
    ],
    "introduction": "Find South American countries together with major landscapes, rivers, islands, and regions.",
    "context": "The vocabulary combines political and physical geography for a broader regional puzzle."
  },
  {
    "order": 31,
    "title": "Prefixes Word Search",
    "categorySegment": "language-arts",
    "slug": "prefixes-word-search",
    "difficulty": "medium",
    "words": [
      "PREFIX",
      "REPLAY",
      "PREVIEW",
      "MISREAD",
      "DISLIKE",
      "UNFAIR",
      "OVERCOOK",
      "UNDERLINE",
      "SUBMARINE",
      "INTERSTATE",
      "ANTISOCIAL",
      "AUTOGRAPH",
      "BICYCLE",
      "TRICYCLE",
      "SEMICIRCLE",
      "MULTICOLOR"
    ],
    "introduction": "Search for words containing common prefixes that change meaning, quantity, direction, or relationship.",
    "context": "The word bank can support a follow-up activity identifying each prefix and discussing what it contributes to the word."
  },
  {
    "order": 32,
    "title": "Suffixes Word Search",
    "categorySegment": "language-arts",
    "slug": "suffixes-word-search",
    "difficulty": "medium",
    "words": [
      "SUFFIX",
      "HELPFUL",
      "CARELESS",
      "MOVEMENT",
      "KINDNESS",
      "TEACHER",
      "ACTOR",
      "READABLE",
      "DANGEROUS",
      "CREATIVE",
      "WOODEN",
      "CHILDHOOD",
      "FRIENDSHIP",
      "QUICKLY",
      "FREEDOM",
      "ARTIST"
    ],
    "introduction": "Find words containing suffixes that affect meaning, word class, or grammatical function.",
    "context": "After solving, the list can be sorted by endings such as ful, less, ness, er, able, and ly."
  },
  {
    "order": 33,
    "title": "Homophones Word Search",
    "categorySegment": "language-arts",
    "slug": "homophones-word-search",
    "difficulty": "medium",
    "words": [
      "THERE",
      "THEIR",
      "THEYRE",
      "TO",
      "TOO",
      "TWO",
      "SEA",
      "SEE",
      "RIGHT",
      "WRITE",
      "SON",
      "SUN",
      "PEAR",
      "PAIR",
      "NIGHT",
      "KNIGHT"
    ],
    "introduction": "Search for eight sets or pairs of words that sound alike while differing in spelling or meaning.",
    "context": "The word bank works best with a follow-up matching or sentence activity that distinguishes the homophones."
  },
  {
    "order": 34,
    "title": "Compound Words Word Search",
    "categorySegment": "language-arts",
    "slug": "compound-words-word-search",
    "difficulty": "medium",
    "words": [
      "SUNFLOWER",
      "RAINBOW",
      "NOTEBOOK",
      "FOOTBALL",
      "BEDROOM",
      "TOOTHBRUSH",
      "AIRPORT",
      "MAILBOX",
      "SNOWMAN",
      "PLAYGROUND",
      "PANCAKE",
      "FIREFLY",
      "KEYBOARD",
      "BOOKSHELF",
      "MOONLIGHT",
      "WATERFALL"
    ],
    "introduction": "Find compound words formed by joining two familiar words into one term.",
    "context": "The puzzle includes objects, places, foods, and nature words that can be separated into their component words after solving."
  },
  {
    "order": 35,
    "title": "Story Elements Word Search",
    "categorySegment": "language-arts",
    "slug": "story-elements-word-search",
    "difficulty": "medium",
    "words": [
      "CHARACTER",
      "SETTING",
      "PLOT",
      "CONFLICT",
      "THEME",
      "BEGINNING",
      "MIDDLE",
      "ENDING",
      "NARRATOR",
      "DIALOGUE",
      "CLIMAX",
      "SOLUTION",
      "EVENT",
      "DETAIL",
      "POINTOFVIEW",
      "SEQUENCE"
    ],
    "introduction": "Search for terms used to describe how stories are organized and understood.",
    "context": "The vocabulary covers characters, setting, events, conflict, narration, and resolution without depending on a specific book."
  },
  {
    "order": 36,
    "title": "Poetry Word Search",
    "categorySegment": "language-arts",
    "slug": "poetry-word-search",
    "difficulty": "medium",
    "words": [
      "POETRY",
      "POEM",
      "VERSE",
      "STANZA",
      "RHYME",
      "RHYTHM",
      "METER",
      "IMAGE",
      "SIMILE",
      "METAPHOR",
      "ALLITERATION",
      "REFRAIN",
      "LINE",
      "SPEAKER",
      "TONE",
      "FORM"
    ],
    "introduction": "Find vocabulary used to discuss poetic structure, sound, imagery, comparison, and voice.",
    "context": "The list supports general poetry review without requiring a specific poem or literary work."
  },
  {
    "order": 37,
    "title": "Shapes Word Search",
    "categorySegment": "math",
    "slug": "shapes-word-search",
    "difficulty": "easy",
    "words": [
      "CIRCLE",
      "SQUARE",
      "TRIANGLE",
      "RECTANGLE",
      "OVAL",
      "DIAMOND",
      "STAR",
      "CUBE",
      "CONE",
      "SPHERE",
      "CYLINDER",
      "PYRAMID"
    ],
    "introduction": "Find common two-dimensional and three-dimensional shape names.",
    "context": "The word list can support a follow-up sorting activity that separates flat shapes from solid figures."
  },
  {
    "order": 38,
    "title": "Measurement Word Search",
    "categorySegment": "math",
    "slug": "measurement-word-search",
    "difficulty": "medium",
    "words": [
      "MEASURE",
      "LENGTH",
      "WIDTH",
      "HEIGHT",
      "DISTANCE",
      "MASS",
      "WEIGHT",
      "VOLUME",
      "CAPACITY",
      "TEMPERATURE",
      "TIME",
      "RULER",
      "SCALE",
      "LITER",
      "METER",
      "CENTIMETER"
    ],
    "introduction": "Search for measurement quantities, tools, and units used in introductory math and science.",
    "context": "The puzzle reviews terminology but does not replace practice choosing units or performing conversions."
  },
  {
    "order": 39,
    "title": "Money Word Search",
    "categorySegment": "math",
    "slug": "money-word-search",
    "difficulty": "easy",
    "words": [
      "MONEY",
      "COIN",
      "BILL",
      "DOLLAR",
      "CENT",
      "PRICE",
      "COST",
      "CHANGE",
      "SAVE",
      "SPEND",
      "BUDGET",
      "TOTAL"
    ],
    "introduction": "Find basic money vocabulary related to prices, coins, bills, saving, spending, and totals.",
    "context": "The puzzle is a terminology activity and must not provide financial advice or claims about financial outcomes."
  },
  {
    "order": 40,
    "title": "Decimals Word Search",
    "categorySegment": "math",
    "slug": "decimals-word-search",
    "difficulty": "medium",
    "words": [
      "DECIMAL",
      "TENTHS",
      "HUNDREDTHS",
      "THOUSANDTHS",
      "POINT",
      "PLACEVALUE",
      "COMPARE",
      "ROUND",
      "ADD",
      "SUBTRACT",
      "MULTIPLY",
      "DIVIDE",
      "FRACTION",
      "PERCENT",
      "EQUIVALENT",
      "NUMBER"
    ],
    "introduction": "Search for decimal-place vocabulary and operations commonly used when working with decimal numbers.",
    "context": "The list connects place value, comparison, rounding, fractions, and percentages in one terminology review."
  },
  {
    "order": 41,
    "title": "Percentages Word Search",
    "categorySegment": "math",
    "slug": "percentages-word-search",
    "difficulty": "medium",
    "words": [
      "PERCENT",
      "HUNDRED",
      "RATE",
      "RATIO",
      "FRACTION",
      "DECIMAL",
      "DISCOUNT",
      "TAX",
      "INTEREST",
      "INCREASE",
      "DECREASE",
      "PROPORTION",
      "WHOLE",
      "PART",
      "CONVERT",
      "CALCULATE"
    ],
    "introduction": "Find vocabulary used when interpreting percentages, rates, discounts, proportions, and parts of a whole.",
    "context": "This is a math-language puzzle and must not be presented as financial, tax, or investment advice."
  },
  {
    "order": 42,
    "title": "Algebra Word Search",
    "categorySegment": "math",
    "slug": "algebra-word-search",
    "difficulty": "medium",
    "words": [
      "ALGEBRA",
      "VARIABLE",
      "CONSTANT",
      "TERM",
      "EXPRESSION",
      "EQUATION",
      "COEFFICIENT",
      "SOLVE",
      "SUBSTITUTE",
      "SIMPLIFY",
      "FACTOR",
      "EXPONENT",
      "INEQUALITY",
      "FUNCTION",
      "GRAPH",
      "FORMULA"
    ],
    "introduction": "Search for algebra vocabulary related to expressions, equations, variables, functions, and symbolic operations.",
    "context": "The page provides terminology review rather than worked solutions or instruction for a particular curriculum."
  },
  {
    "order": 43,
    "title": "Tennis Word Search",
    "categorySegment": "sports",
    "slug": "tennis-word-search",
    "difficulty": "medium",
    "words": [
      "TENNIS",
      "RACKET",
      "BALL",
      "COURT",
      "NET",
      "SERVE",
      "VOLLEY",
      "FOREHAND",
      "BACKHAND",
      "BASELINE",
      "DEUCE",
      "MATCH",
      "SET",
      "GAME",
      "UMPIRE",
      "TOURNAMENT"
    ],
    "introduction": "Find tennis equipment, court features, strokes, scoring words, and competition vocabulary.",
    "context": "The puzzle focuses on the sport generally and does not use professional player or tournament branding."
  },
  {
    "order": 44,
    "title": "Volleyball Word Search",
    "categorySegment": "sports",
    "slug": "volleyball-word-search",
    "difficulty": "medium",
    "words": [
      "VOLLEYBALL",
      "NET",
      "SERVE",
      "SPIKE",
      "BLOCK",
      "SETTER",
      "LIBERO",
      "DIG",
      "ROTATION",
      "COURT",
      "TEAM",
      "RALLY",
      "POINT",
      "PASS",
      "MATCH",
      "REFEREE"
    ],
    "introduction": "Search for volleyball skills, positions, court features, and match vocabulary.",
    "context": "The word list works for indoor or general volleyball themes without depending on a particular team or league."
  },
  {
    "order": 45,
    "title": "Swimming Word Search",
    "categorySegment": "sports",
    "slug": "swimming-word-search",
    "difficulty": "medium",
    "words": [
      "SWIMMING",
      "POOL",
      "LANE",
      "STROKE",
      "FREESTYLE",
      "BACKSTROKE",
      "BREASTSTROKE",
      "BUTTERFLY",
      "DIVE",
      "TURN",
      "GOGGLES",
      "CAP",
      "LAP",
      "RELAY",
      "KICK",
      "FLOAT"
    ],
    "introduction": "Find swimming strokes, equipment, pool features, and race vocabulary.",
    "context": "The puzzle is a vocabulary activity and must not be treated as water-safety or swimming instruction."
  },
  {
    "order": 46,
    "title": "Track and Field Word Search",
    "categorySegment": "sports",
    "slug": "track-and-field-word-search",
    "difficulty": "medium",
    "words": [
      "TRACK",
      "FIELD",
      "SPRINT",
      "RELAY",
      "HURDLES",
      "JAVELIN",
      "DISCUS",
      "SHOTPUT",
      "LONGJUMP",
      "HIGHJUMP",
      "MARATHON",
      "RUNNER",
      "BATON",
      "LANE",
      "FINISH",
      "STADIUM"
    ],
    "introduction": "Search for running, jumping, and throwing events found in track-and-field competitions.",
    "context": "The vocabulary covers event types and basic competition equipment without naming professional athletes or branded events."
  },
  {
    "order": 47,
    "title": "Gymnastics Word Search",
    "categorySegment": "sports",
    "slug": "gymnastics-word-search",
    "difficulty": "medium",
    "words": [
      "GYMNASTICS",
      "BEAM",
      "BARS",
      "VAULT",
      "FLOOR",
      "ROUTINE",
      "BALANCE",
      "TUMBLE",
      "LANDING",
      "SPIN",
      "LEAP",
      "COACH",
      "SCORE",
      "FLEXIBILITY",
      "STRENGTH",
      "TEAM"
    ],
    "introduction": "Find gymnastics apparatus, movement, routine, and competition vocabulary.",
    "context": "The puzzle describes the sport generally and does not provide training, flexibility, or injury-prevention instructions."
  },
  {
    "order": 48,
    "title": "Golf Word Search",
    "categorySegment": "sports",
    "slug": "golf-word-search",
    "difficulty": "easy",
    "words": [
      "GOLF",
      "CLUB",
      "BALL",
      "TEE",
      "GREEN",
      "FAIRWAY",
      "HOLE",
      "PUTT",
      "DRIVE",
      "CADDIE",
      "BUNKER",
      "COURSE"
    ],
    "introduction": "Find basic golf equipment, course features, and common playing terms.",
    "context": "The compact vocabulary list creates a quick sports puzzle without using tournament, course, or player names."
  },
  {
    "order": 49,
    "title": "School Subjects Word Search",
    "categorySegment": "classroom-values",
    "slug": "school-subjects-word-search",
    "difficulty": "easy",
    "words": [
      "MATH",
      "SCIENCE",
      "READING",
      "WRITING",
      "HISTORY",
      "GEOGRAPHY",
      "ART",
      "MUSIC",
      "HEALTH",
      "LANGUAGE",
      "COMPUTER",
      "DRAMA"
    ],
    "introduction": "Search for familiar subjects and learning areas found in many school schedules.",
    "context": "The list is intentionally broad and does not imply that every school uses the same subjects or course names."
  },
  {
    "order": 50,
    "title": "Study Skills Word Search",
    "categorySegment": "classroom-values",
    "slug": "study-skills-word-search",
    "difficulty": "medium",
    "words": [
      "STUDY",
      "PLAN",
      "NOTES",
      "REVIEW",
      "PRACTICE",
      "FOCUS",
      "SCHEDULE",
      "ORGANIZE",
      "HIGHLIGHT",
      "SUMMARIZE",
      "QUESTION",
      "EXPLAIN",
      "REMEMBER",
      "BREAK",
      "GOAL",
      "CHECKLIST"
    ],
    "introduction": "Find vocabulary connected with planning, reviewing, organizing, and checking school work.",
    "context": "The page presents general study terms without promising grades, memory improvement, or academic outcomes."
  },
  {
    "order": 51,
    "title": "Teamwork Word Search",
    "categorySegment": "classroom-values",
    "slug": "teamwork-word-search",
    "difficulty": "easy",
    "words": [
      "TEAMWORK",
      "SHARE",
      "LISTEN",
      "HELP",
      "PLAN",
      "COOPERATE",
      "RESPECT",
      "SUPPORT",
      "TRUST",
      "GROUP",
      "TOGETHER",
      "SUCCESS"
    ],
    "introduction": "Find words describing practical cooperation, communication, planning, and shared responsibility.",
    "context": "The puzzle can support a discussion about group behavior without claiming social or developmental outcomes."
  },
  {
    "order": 52,
    "title": "Respect Word Search",
    "categorySegment": "classroom-values",
    "slug": "respect-word-search",
    "difficulty": "easy",
    "words": [
      "RESPECT",
      "LISTEN",
      "KIND",
      "POLITE",
      "FAIR",
      "HONEST",
      "PATIENT",
      "INCLUDE",
      "CARE",
      "MANNERS",
      "BOUNDARY",
      "TRUST"
    ],
    "introduction": "Search for words connected with listening, fairness, personal boundaries, honesty, and considerate behavior.",
    "context": "The page is a vocabulary and discussion activity, not behavioral treatment or professional guidance."
  },
  {
    "order": 53,
    "title": "Gratitude Word Search",
    "categorySegment": "classroom-values",
    "slug": "gratitude-word-search",
    "difficulty": "easy",
    "words": [
      "GRATITUDE",
      "THANKFUL",
      "APPRECIATE",
      "KINDNESS",
      "FAMILY",
      "FRIENDS",
      "HOME",
      "FOOD",
      "NATURE",
      "HELP",
      "SHARE",
      "NOTICE"
    ],
    "introduction": "Find words associated with appreciation, supportive people, everyday resources, and noticing positive experiences.",
    "context": "The puzzle avoids mental-health claims and functions only as a general values-themed activity."
  },
  {
    "order": 54,
    "title": "Goals Word Search",
    "categorySegment": "classroom-values",
    "slug": "goals-word-search",
    "difficulty": "easy",
    "words": [
      "GOAL",
      "PLAN",
      "STEP",
      "EFFORT",
      "PRACTICE",
      "FOCUS",
      "PROGRESS",
      "CHECK",
      "ADJUST",
      "FINISH",
      "LEARN",
      "SUCCESS"
    ],
    "introduction": "Search for words connected with setting a goal, making a plan, checking progress, and adjusting steps.",
    "context": "The vocabulary provides a simple planning theme without promising achievement or educational outcomes."
  },
  {
    "order": 55,
    "title": "Valentine’s Day Word Search",
    "categorySegment": "holidays",
    "slug": "valentines-day-word-search",
    "difficulty": "medium",
    "words": [
      "VALENTINE",
      "HEART",
      "CARD",
      "FLOWERS",
      "CHOCOLATE",
      "FRIENDSHIP",
      "KINDNESS",
      "MESSAGE",
      "CUPID",
      "RIBBON",
      "CANDY",
      "PINK",
      "RED",
      "FEBRUARY",
      "CELEBRATE",
      "AFFECTION"
    ],
    "introduction": "Find Valentine’s Day cards, colors, treats, decorations, and friendship vocabulary.",
    "context": "The puzzle uses generic holiday imagery and avoids branded characters, entertainment properties, or commercial products."
  },
  {
    "order": 56,
    "title": "St. Patrick’s Day Word Search",
    "categorySegment": "holidays",
    "slug": "st-patricks-day-word-search",
    "difficulty": "medium",
    "words": [
      "SHAMROCK",
      "IRELAND",
      "GREEN",
      "PARADE",
      "MARCH",
      "CLOVER",
      "RAINBOW",
      "GOLD",
      "TRADITION",
      "MUSIC",
      "DANCE",
      "CELEBRATE",
      "LUCK",
      "FESTIVAL",
      "HARP",
      "EMERALD"
    ],
    "introduction": "Search for colors, symbols, music, and celebration vocabulary associated with St. Patrick’s Day.",
    "context": "The page uses general cultural and holiday terms without presenting folklore as historical fact."
  },
  {
    "order": 57,
    "title": "Easter Word Search",
    "categorySegment": "holidays",
    "slug": "easter-word-search",
    "difficulty": "medium",
    "words": [
      "EASTER",
      "SPRING",
      "BASKET",
      "EGG",
      "BUNNY",
      "FLOWERS",
      "CHICK",
      "PASTEL",
      "HUNT",
      "BONNET",
      "GARDEN",
      "SUNSHINE",
      "CELEBRATE",
      "FAMILY",
      "SUNDAY",
      "CHOCOLATE"
    ],
    "introduction": "Find familiar Easter and springtime vocabulary, including baskets, eggs, flowers, and family activities.",
    "context": "The selected terms create a broad seasonal page without depending on copyrighted characters or commercial products."
  },
  {
    "order": 58,
    "title": "Thanksgiving Word Search",
    "categorySegment": "holidays",
    "slug": "thanksgiving-word-search",
    "difficulty": "medium",
    "words": [
      "THANKSGIVING",
      "HARVEST",
      "FAMILY",
      "DINNER",
      "TURKEY",
      "STUFFING",
      "PUMPKIN",
      "CRANBERRY",
      "GRATITUDE",
      "AUTUMN",
      "PARADE",
      "FEAST",
      "CORN",
      "PIE",
      "TRADITION",
      "NOVEMBER"
    ],
    "introduction": "Search for Thanksgiving foods, gatherings, harvest vocabulary, and seasonal traditions.",
    "context": "The page presents familiar modern holiday terms without making detailed historical claims."
  },
  {
    "order": 59,
    "title": "New Year Word Search",
    "categorySegment": "holidays",
    "slug": "new-year-word-search",
    "difficulty": "easy",
    "words": [
      "NEWYEAR",
      "MIDNIGHT",
      "COUNTDOWN",
      "CALENDAR",
      "JANUARY",
      "RESOLUTION",
      "CLOCK",
      "CELEBRATE",
      "FIREWORKS",
      "CONFETTI",
      "PARTY",
      "BEGINNING"
    ],
    "introduction": "Find words connected with calendars, midnight celebrations, countdowns, and the beginning of a new year.",
    "context": "The compact puzzle uses general New Year vocabulary suitable for home or classroom use."
  },
  {
    "order": 60,
    "title": "Mother’s Day Word Search",
    "categorySegment": "holidays",
    "slug": "mothers-day-word-search",
    "difficulty": "easy",
    "words": [
      "MOTHER",
      "FAMILY",
      "CARD",
      "FLOWERS",
      "BREAKFAST",
      "THANKS",
      "LOVE",
      "KINDNESS",
      "HUG",
      "CELEBRATE",
      "MAY",
      "MEMORIES"
    ],
    "introduction": "Search for words connected with cards, flowers, family activities, appreciation, and Mother’s Day.",
    "context": "Use inclusive supporting copy that acknowledges families may recognize caregivers and important adults in different ways."
  },
  {
    "order": 61,
    "title": "Ancient Egypt Word Search",
    "categorySegment": "history",
    "slug": "ancient-egypt-word-search",
    "difficulty": "hard",
    "words": [
      "EGYPT",
      "PHARAOH",
      "PYRAMID",
      "NILE",
      "SPHINX",
      "HIEROGLYPH",
      "MUMMY",
      "TEMPLE",
      "PAPYRUS",
      "SCRIBE",
      "DYNASTY",
      "DESERT",
      "TOMB",
      "SARCOPHAGUS",
      "GIZA",
      "OSIRIS",
      "ANUBIS",
      "CLEOPATRA",
      "MEMPHIS",
      "OBELISK"
    ],
    "introduction": "Find names, places, objects, writing systems, and religious vocabulary associated with ancient Egypt.",
    "context": "The page is a general historical vocabulary review and should avoid unsupported dates, sensational claims, or fictional portrayals."
  },
  {
    "order": 62,
    "title": "Ancient Greece Word Search",
    "categorySegment": "history",
    "slug": "ancient-greece-word-search",
    "difficulty": "hard",
    "words": [
      "GREECE",
      "ATHENS",
      "SPARTA",
      "OLYMPICS",
      "ACROPOLIS",
      "PARTHENON",
      "PHILOSOPHY",
      "DEMOCRACY",
      "MYTHOLOGY",
      "THEATER",
      "HOMER",
      "SOCRATES",
      "PLATO",
      "ARISTOTLE",
      "ZEUS",
      "ATHENA",
      "HOPLITE",
      "POLIS",
      "MARATHON",
      "AEGEAN"
    ],
    "introduction": "Search for places, institutions, thinkers, mythology, and civic vocabulary associated with ancient Greece.",
    "context": "The puzzle brings together broad historical terms without claiming that every word belongs to the same period or city-state."
  },
  {
    "order": 63,
    "title": "Ancient Rome Word Search",
    "categorySegment": "history",
    "slug": "ancient-rome-word-search",
    "difficulty": "hard",
    "words": [
      "ROME",
      "EMPIRE",
      "REPUBLIC",
      "SENATE",
      "LEGION",
      "COLOSSEUM",
      "AQUEDUCT",
      "FORUM",
      "GLADIATOR",
      "CAESAR",
      "AUGUSTUS",
      "LATIN",
      "PATRICIAN",
      "PLEBEIAN",
      "CONSUL",
      "PROVINCE",
      "ROAD",
      "TEMPLE",
      "VILLA",
      "MEDITERRANEAN"
    ],
    "introduction": "Find political, military, architectural, social, and geographic vocabulary associated with ancient Rome.",
    "context": "The word list spans the Republic and Empire and should be described as a broad review rather than one historical moment."
  },
  {
    "order": 64,
    "title": "Medieval Times Word Search",
    "categorySegment": "history",
    "slug": "medieval-times-word-search",
    "difficulty": "medium",
    "words": [
      "MEDIEVAL",
      "CASTLE",
      "KNIGHT",
      "KINGDOM",
      "VILLAGE",
      "MARKET",
      "GUILD",
      "BLACKSMITH",
      "ARMOR",
      "SHIELD",
      "TOWER",
      "MOAT",
      "MANOR",
      "MONASTERY",
      "HARVEST",
      "FEAST"
    ],
    "introduction": "Search for places, occupations, objects, and institutions commonly discussed in medieval-history units.",
    "context": "Avoid presenting fictional castle stories or modern fantasy conventions as historical fact."
  },
  {
    "order": 65,
    "title": "Renaissance Word Search",
    "categorySegment": "history",
    "slug": "renaissance-word-search",
    "difficulty": "medium",
    "words": [
      "RENAISSANCE",
      "ART",
      "SCIENCE",
      "HUMANISM",
      "PAINTING",
      "SCULPTURE",
      "INVENTION",
      "PRINTING",
      "FLORENCE",
      "VENICE",
      "PATRON",
      "WORKSHOP",
      "ANATOMY",
      "PERSPECTIVE",
      "EXPLORATION",
      "LEARNING"
    ],
    "introduction": "Find words connected with Renaissance art, learning, workshops, printing, and changing approaches to observation.",
    "context": "The page provides broad period vocabulary without reducing the Renaissance to a single person or invention."
  },
  {
    "order": 66,
    "title": "Industrial Revolution Word Search",
    "categorySegment": "history",
    "slug": "industrial-revolution-word-search",
    "difficulty": "hard",
    "words": [
      "INDUSTRY",
      "FACTORY",
      "STEAM",
      "ENGINE",
      "TEXTILE",
      "MACHINE",
      "RAILWAY",
      "COAL",
      "IRON",
      "URBANIZATION",
      "INVENTION",
      "WORKER",
      "PRODUCTION",
      "TRANSPORT",
      "CANAL",
      "LOCOMOTIVE",
      "POWER",
      "MILL",
      "MANUFACTURING",
      "TECHNOLOGY"
    ],
    "introduction": "Search for manufacturing, energy, transportation, labor, and urban vocabulary associated with industrialization.",
    "context": "The puzzle is a terminology review and should not oversimplify the period’s social, regional, or economic effects."
  },
  {
    "order": 67,
    "title": "Airport Word Search",
    "categorySegment": "travel",
    "slug": "airport-word-search",
    "difficulty": "medium",
    "words": [
      "AIRPORT",
      "TERMINAL",
      "GATE",
      "PASSPORT",
      "TICKET",
      "LUGGAGE",
      "SECURITY",
      "BOARDING",
      "RUNWAY",
      "FLIGHT",
      "PILOT",
      "CABIN",
      "DEPARTURE",
      "ARRIVAL",
      "BAGGAGE",
      "CUSTOMS"
    ],
    "introduction": "Find airport locations, documents, flight stages, and common passenger vocabulary.",
    "context": "The page is a travel-language activity and must not replace official airport, customs, or security instructions."
  },
  {
    "order": 68,
    "title": "Road Trip Word Search",
    "categorySegment": "travel",
    "slug": "road-trip-word-search",
    "difficulty": "easy",
    "words": [
      "ROADTRIP",
      "CAR",
      "MAP",
      "ROUTE",
      "HIGHWAY",
      "MOTEL",
      "SNACKS",
      "MUSIC",
      "CAMERA",
      "LUGGAGE",
      "STOP",
      "DESTINATION"
    ],
    "introduction": "Search for common road-trip planning, travel, and rest-stop vocabulary.",
    "context": "The compact puzzle works as a printable travel activity without promoting distracted driving or use by the driver."
  },
  {
    "order": 69,
    "title": "Hotel Word Search",
    "categorySegment": "travel",
    "slug": "hotel-word-search",
    "difficulty": "easy",
    "words": [
      "HOTEL",
      "ROOM",
      "LOBBY",
      "KEY",
      "RECEPTION",
      "ELEVATOR",
      "TOWEL",
      "PILLOW",
      "RESERVATION",
      "GUEST",
      "CHECKIN",
      "BREAKFAST"
    ],
    "introduction": "Find words associated with hotel rooms, reservations, guest services, and shared building areas.",
    "context": "The vocabulary can support general travel or ESL practice without referring to a particular hotel brand."
  },
  {
    "order": 70,
    "title": "Train Travel Word Search",
    "categorySegment": "travel",
    "slug": "train-travel-word-search",
    "difficulty": "medium",
    "words": [
      "TRAIN",
      "STATION",
      "PLATFORM",
      "TICKET",
      "TRACK",
      "ENGINE",
      "CARRIAGE",
      "CONDUCTOR",
      "TIMETABLE",
      "DEPARTURE",
      "ARRIVAL",
      "JOURNEY",
      "RAILWAY",
      "SEAT",
      "LUGGAGE",
      "SIGNAL"
    ],
    "introduction": "Search for train stations, schedules, vehicles, staff, and journey vocabulary.",
    "context": "The puzzle uses general rail-travel terms and must not replace local timetable or safety information."
  },
  {
    "order": 71,
    "title": "Cruise Travel Word Search",
    "categorySegment": "travel",
    "slug": "cruise-travel-word-search",
    "difficulty": "medium",
    "words": [
      "CRUISE",
      "SHIP",
      "CABIN",
      "DECK",
      "PORT",
      "HARBOR",
      "OCEAN",
      "CAPTAIN",
      "VOYAGE",
      "DINING",
      "EXCURSION",
      "LUGGAGE",
      "LIFEBOAT",
      "ITINERARY",
      "TERMINAL",
      "SAILING"
    ],
    "introduction": "Find ship areas, voyage planning, ports, and passenger-travel vocabulary.",
    "context": "The page is a generic cruise theme without referencing operators, ships, destinations, or safety procedures."
  },
  {
    "order": 72,
    "title": "Vacation Word Search",
    "categorySegment": "travel",
    "slug": "vacation-word-search",
    "difficulty": "easy",
    "words": [
      "VACATION",
      "TRAVEL",
      "HOTEL",
      "BEACH",
      "MOUNTAIN",
      "CAMERA",
      "LUGGAGE",
      "TICKET",
      "MAP",
      "RELAX",
      "VISIT",
      "MEMORIES"
    ],
    "introduction": "Search for travel planning, destinations, activities, and keepsake vocabulary connected with vacations.",
    "context": "The broad theme works as a pre-trip or rainy-day printable without promoting a particular destination or company."
  },
  {
    "order": 73,
    "title": "Musical Instruments Word Search",
    "categorySegment": "music",
    "slug": "musical-instruments-word-search",
    "difficulty": "medium",
    "words": [
      "PIANO",
      "GUITAR",
      "VIOLIN",
      "DRUMS",
      "TRUMPET",
      "FLUTE",
      "CLARINET",
      "SAXOPHONE",
      "CELLO",
      "HARP",
      "TROMBONE",
      "OBOE",
      "BANJO",
      "UKULELE",
      "CYMBALS",
      "BASSOON"
    ],
    "introduction": "Find string, woodwind, brass, keyboard, and percussion instruments.",
    "context": "The list spans several instrument families and does not depend on a particular orchestra, performer, or music brand."
  },
  {
    "order": 74,
    "title": "Orchestra Word Search",
    "categorySegment": "music",
    "slug": "orchestra-word-search",
    "difficulty": "hard",
    "words": [
      "ORCHESTRA",
      "CONDUCTOR",
      "VIOLIN",
      "VIOLA",
      "CELLO",
      "BASS",
      "FLUTE",
      "OBOE",
      "CLARINET",
      "BASSOON",
      "TRUMPET",
      "TROMBONE",
      "HORN",
      "TUBA",
      "PERCUSSION",
      "HARP",
      "SCORE",
      "SECTION",
      "TEMPO",
      "CONCERT"
    ],
    "introduction": "Search for orchestral instruments, sections, performance roles, and musical vocabulary.",
    "context": "The larger grid reflects the broad instrument inventory and provides a more demanding music puzzle."
  },
  {
    "order": 75,
    "title": "Piano Word Search",
    "categorySegment": "music",
    "slug": "piano-word-search",
    "difficulty": "medium",
    "words": [
      "PIANO",
      "KEYBOARD",
      "KEY",
      "PEDAL",
      "MELODY",
      "CHORD",
      "SCALE",
      "OCTAVE",
      "RHYTHM",
      "TEMPO",
      "NOTE",
      "SONATA",
      "PRACTICE",
      "BENCH",
      "SUSTAIN",
      "RECITAL"
    ],
    "introduction": "Find piano parts, playing vocabulary, musical structures, and performance terms.",
    "context": "The puzzle is a terminology activity and does not provide playing technique or practice advice."
  },
  {
    "order": 76,
    "title": "Guitar Word Search",
    "categorySegment": "music",
    "slug": "guitar-word-search",
    "difficulty": "medium",
    "words": [
      "GUITAR",
      "STRING",
      "FRET",
      "CHORD",
      "PICK",
      "STRUM",
      "RHYTHM",
      "MELODY",
      "ACOUSTIC",
      "ELECTRIC",
      "AMPLIFIER",
      "TUNING",
      "BRIDGE",
      "NECK",
      "SOLO",
      "PRACTICE"
    ],
    "introduction": "Search for guitar parts, playing actions, sound equipment, and common music vocabulary.",
    "context": "The list applies broadly to acoustic and electric guitars without mentioning manufacturers or performers."
  },
  {
    "order": 77,
    "title": "Music Theory Word Search",
    "categorySegment": "music",
    "slug": "music-theory-word-search",
    "difficulty": "hard",
    "words": [
      "RHYTHM",
      "MELODY",
      "HARMONY",
      "TEMPO",
      "METER",
      "SCALE",
      "CHORD",
      "INTERVAL",
      "KEY",
      "TONIC",
      "DOMINANT",
      "MAJOR",
      "MINOR",
      "OCTAVE",
      "NOTATION",
      "CLEF",
      "REST",
      "BEAT",
      "DYNAMICS",
      "CADENCE"
    ],
    "introduction": "Find foundational music-theory vocabulary related to pitch, rhythm, harmony, notation, and musical form.",
    "context": "The page provides a broad terminology review rather than a complete theory lesson."
  },
  {
    "order": 78,
    "title": "Singing Word Search",
    "categorySegment": "music",
    "slug": "singing-word-search",
    "difficulty": "easy",
    "words": [
      "SINGING",
      "VOICE",
      "SONG",
      "MELODY",
      "RHYTHM",
      "BREATH",
      "PITCH",
      "CHORUS",
      "VERSE",
      "MICROPHONE",
      "PRACTICE",
      "PERFORM"
    ],
    "introduction": "Find words connected with songs, vocal performance, musical structure, and rehearsal.",
    "context": "The puzzle is a music-vocabulary activity and must not provide vocal-health or technique claims."
  },
  {
    "order": 79,
    "title": "Reading Word Search",
    "categorySegment": "books-and-reading",
    "slug": "reading-word-search",
    "difficulty": "easy",
    "words": [
      "READING",
      "BOOK",
      "PAGE",
      "STORY",
      "CHAPTER",
      "AUTHOR",
      "TITLE",
      "WORD",
      "LETTER",
      "LIBRARY",
      "QUIET",
      "LEARN"
    ],
    "introduction": "Search for familiar vocabulary connected with books, stories, pages, authors, and reading spaces.",
    "context": "The page is a general reading-themed activity and must not promise literacy or academic improvement."
  },
  {
    "order": 80,
    "title": "Library Word Search",
    "categorySegment": "books-and-reading",
    "slug": "library-word-search",
    "difficulty": "easy",
    "words": [
      "LIBRARY",
      "BOOK",
      "SHELF",
      "CATALOG",
      "AUTHOR",
      "READER",
      "BORROW",
      "RETURN",
      "CARD",
      "STUDY",
      "REFERENCE",
      "LIBRARIAN"
    ],
    "introduction": "Find words connected with library collections, borrowing, reference materials, and library staff.",
    "context": "The vocabulary applies to many public and school libraries without claiming that every library uses the same systems."
  },
  {
    "order": 81,
    "title": "Book Genres Word Search",
    "categorySegment": "books-and-reading",
    "slug": "book-genres-word-search",
    "difficulty": "medium",
    "words": [
      "FICTION",
      "NONFICTION",
      "MYSTERY",
      "FANTASY",
      "SCIENCEFICTION",
      "BIOGRAPHY",
      "HISTORY",
      "POETRY",
      "ADVENTURE",
      "ROMANCE",
      "THRILLER",
      "MEMOIR",
      "CLASSIC",
      "HUMOR",
      "GRAPHICNOVEL",
      "FOLKTALE"
    ],
    "introduction": "Search for common book genres and broad forms of writing found in libraries and bookstores.",
    "context": "The list uses general categories and does not reference specific copyrighted works or authors."
  },
  {
    "order": 82,
    "title": "Book Parts Word Search",
    "categorySegment": "books-and-reading",
    "slug": "book-parts-word-search",
    "difficulty": "medium",
    "words": [
      "COVER",
      "SPINE",
      "TITLE",
      "AUTHOR",
      "PAGE",
      "CHAPTER",
      "CONTENTS",
      "INDEX",
      "GLOSSARY",
      "PREFACE",
      "APPENDIX",
      "CAPTION",
      "ILLUSTRATION",
      "PARAGRAPH",
      "HEADING",
      "FOOTNOTE"
    ],
    "introduction": "Find physical and organizational parts that help readers navigate a book.",
    "context": "The vocabulary includes exterior features, text divisions, and reference sections used in fiction and nonfiction."
  },
  {
    "order": 83,
    "title": "Nonfiction Text Features Word Search",
    "categorySegment": "books-and-reading",
    "slug": "nonfiction-text-features-word-search",
    "difficulty": "medium",
    "words": [
      "NONFICTION",
      "HEADING",
      "SUBHEADING",
      "CAPTION",
      "DIAGRAM",
      "CHART",
      "MAP",
      "TIMELINE",
      "INDEX",
      "GLOSSARY",
      "CONTENTS",
      "PHOTO",
      "LABEL",
      "SIDEBAR",
      "KEYWORD",
      "SUMMARY"
    ],
    "introduction": "Search for text features used to organize and explain information in nonfiction books and articles.",
    "context": "The word bank can support a follow-up activity locating each feature in an appropriate nonfiction text."
  },
  {
    "order": 84,
    "title": "Storytelling Word Search",
    "categorySegment": "books-and-reading",
    "slug": "storytelling-word-search",
    "difficulty": "medium",
    "words": [
      "STORYTELLING",
      "CHARACTER",
      "SETTING",
      "BEGINNING",
      "MIDDLE",
      "ENDING",
      "VOICE",
      "DETAIL",
      "SEQUENCE",
      "CONFLICT",
      "SOLUTION",
      "AUDIENCE",
      "DIALOGUE",
      "DESCRIPTION",
      "IMAGINATION",
      "NARRATOR"
    ],
    "introduction": "Find vocabulary used when planning, telling, revising, and discussing a story.",
    "context": "The page focuses on general storytelling elements and does not depend on a particular book, film, or character."
  },
  {
    "order": 85,
    "title": "Colors Word Search",
    "categorySegment": "art",
    "slug": "colors-word-search",
    "difficulty": "easy",
    "words": [
      "RED",
      "ORANGE",
      "YELLOW",
      "GREEN",
      "BLUE",
      "PURPLE",
      "PINK",
      "BROWN",
      "BLACK",
      "WHITE",
      "GRAY",
      "GOLD"
    ],
    "introduction": "Find twelve familiar color names in a compact forward-only puzzle.",
    "context": "The puzzle provides basic art and descriptive vocabulary without implying that the list contains every color or shade."
  },
  {
    "order": 86,
    "title": "Painting Word Search",
    "categorySegment": "art",
    "slug": "painting-word-search",
    "difficulty": "medium",
    "words": [
      "PAINTING",
      "CANVAS",
      "BRUSH",
      "PALETTE",
      "COLOR",
      "PIGMENT",
      "EASEL",
      "ACRYLIC",
      "WATERCOLOR",
      "OIL",
      "LAYER",
      "TEXTURE",
      "SHADE",
      "HIGHLIGHT",
      "PORTRAIT",
      "LANDSCAPE"
    ],
    "introduction": "Search for painting materials, media, techniques, and common subject types.",
    "context": "The page supplies art vocabulary without giving chemical, ventilation, or material-safety instructions."
  },
  {
    "order": 87,
    "title": "Drawing Word Search",
    "categorySegment": "art",
    "slug": "drawing-word-search",
    "difficulty": "easy",
    "words": [
      "DRAWING",
      "PENCIL",
      "PAPER",
      "LINE",
      "SHAPE",
      "SHADE",
      "SKETCH",
      "ERASER",
      "OUTLINE",
      "DETAIL",
      "PORTRAIT",
      "PATTERN"
    ],
    "introduction": "Find basic drawing materials, marks, and planning vocabulary.",
    "context": "The compact puzzle works as an introductory art activity without prescribing a particular drawing method."
  },
  {
    "order": 88,
    "title": "Sculpture Word Search",
    "categorySegment": "art",
    "slug": "sculpture-word-search",
    "difficulty": "medium",
    "words": [
      "SCULPTURE",
      "CLAY",
      "STONE",
      "METAL",
      "WOOD",
      "CARVE",
      "MODEL",
      "FORM",
      "TEXTURE",
      "STATUE",
      "CHISEL",
      "CAST",
      "RELIEF",
      "FIGURE",
      "STUDIO",
      "PEDESTAL"
    ],
    "introduction": "Search for sculpture materials, processes, forms, tools, and display vocabulary.",
    "context": "The puzzle is an art-terminology resource and must not provide instructions for hazardous tools or materials."
  },
  {
    "order": 89,
    "title": "Photography Word Search",
    "categorySegment": "art",
    "slug": "photography-word-search",
    "difficulty": "medium",
    "words": [
      "PHOTOGRAPHY",
      "CAMERA",
      "LENS",
      "FOCUS",
      "SHUTTER",
      "EXPOSURE",
      "APERTURE",
      "FLASH",
      "TRIPOD",
      "PORTRAIT",
      "LANDSCAPE",
      "COMPOSITION",
      "LIGHT",
      "FRAME",
      "IMAGE",
      "ZOOM"
    ],
    "introduction": "Find camera parts, settings, image types, and composition vocabulary.",
    "context": "The word list applies to photography generally without referring to a camera manufacturer, product, or professional service."
  },
  {
    "order": 90,
    "title": "Crafts Word Search",
    "categorySegment": "art",
    "slug": "crafts-word-search",
    "difficulty": "easy",
    "words": [
      "CRAFTS",
      "PAPER",
      "GLUE",
      "SCISSORS",
      "YARN",
      "FABRIC",
      "BEADS",
      "PAINT",
      "FOLD",
      "CUT",
      "DESIGN",
      "CREATE"
    ],
    "introduction": "Search for common craft materials, tools, and creative actions.",
    "context": "The page is a vocabulary activity and must not give age-specific or tool-safety assurances."
  }
];

const sizes: Record<Difficulty, number> = { easy: 12, medium: 15, hard: 18 };
const outputSentences = [
  "Play online or print the matching PDF and answer key.",
  "Use it online, on paper, or as a PDF with answers.",
  "Open the online puzzle or prepare a printable PDF and solution.",
  "Play in your browser, print it, or download the puzzle and key.",
  "The reviewed grid supports online play, printing, PDF, and answers.",
  "Choose online play or a printable puzzle with PDF and solution options."
];

export interface CuratedTopicPrompt6 extends CuratedTopicPrompt6Source {
  topicSlug: string;
  routeSlug: string;
  categorySlug: string;
  audience: string[];
  seed: string;
  reviewedOn: string;
  rows: number;
  columns: number;
  difficultyNote: string;
  printNote: string;
  metaTitle: string;
  metaDescription: string;
}

export const curatedTopicsPrompt6: CuratedTopicPrompt6[] = sourceTopics.map((topic, index) => {
  const subject = topic.title.replace(/ Word Search$/, "").toLocaleLowerCase("en-US");
  const representative = topic.words.slice(0, 3).map((word) => word.toLocaleLowerCase("en-US")).join(", ");
  const metaTitle = topic.difficulty === "easy"
    ? `${topic.title} | Easy Printable Puzzle`
    : topic.difficulty === "hard"
      ? `${topic.title} | Challenging Printable Puzzle`
      : index % 2
        ? `${topic.title} | Printable Puzzle with Answers`
        : `${topic.title} | Free Printable and Online`;
  return {
    ...topic,
    topicSlug: topic.slug,
    routeSlug: `${topic.categorySegment}/${topic.slug}`,
    categorySlug: categorySlugs[topic.categorySegment],
    audience: audiences[topic.categorySegment],
    seed: `curated-${topic.slug}-v1`,
    reviewedOn: PROMPT_6_REVIEW_DATE,
    rows: sizes[topic.difficulty],
    columns: sizes[topic.difficulty],
    difficultyNote: topic.difficulty === "easy"
      ? "This Easy puzzle uses a 12 by 12 grid with twelve words and forward-only horizontal, vertical, or diagonal paths."
      : topic.difficulty === "medium"
        ? "This Medium puzzle uses a 15 by 15 grid with sixteen words placed in all eight straight directions."
        : "This Hard puzzle uses an 18 by 18 grid with twenty words, overlap, reverse paths, and diagonal placements.",
    printNote: `The printable ${subject} grid keeps ${topic.words[0]} and the other ${topic.words.length - 1} reviewed terms aligned with its PDF and answer page.`,
    metaTitle,
    metaDescription: `Find ${representative} and related ${subject} vocabulary. ${outputSentences[index % outputSentences.length]}`
  };
});
