import type { Difficulty } from "@/lib/puzzle/types";

export const CURATED_REVIEW_DATE = "2026-07-25";

const categoryDetails = {
  Animals: { segment: "animals", slug: "animals-word-searches" },
  Food: { segment: "food-and-drink", slug: "food-and-drink-word-searches" },
  Nature: { segment: "nature-and-weather", slug: "nature-and-weather-word-searches" },
  Science: { segment: "science", slug: "science-word-searches" },
  Geography: { segment: "geography", slug: "geography-word-searches" },
  "Language Arts": { segment: "language-arts", slug: "language-arts-word-searches" },
  Math: { segment: "math", slug: "math-word-searches" },
  Sports: { segment: "sports", slug: "sports-word-searches" },
  Classroom: { segment: "classroom-values", slug: "classroom-and-values-word-searches" },
  Values: { segment: "classroom-values", slug: "classroom-and-values-word-searches" },
  "Seasons and Holidays": { segment: "holidays", slug: "holiday-word-searches" }
} as const;

interface CuratedTopicSource {
  order: number;
  title: string;
  category: keyof typeof categoryDetails;
  slug: string;
  difficulty: Difficulty;
  audience: string[];
  seed: string;
  words: string[];
  introduction: string;
  context: string;
  difficultyNote: string;
  metaTitle: string;
  metaDescription: string;
}

const curatedTopicSource: CuratedTopicSource[] = [
  {
    "order": 1,
    "title": "Dog Word Search",
    "category": "Animals",
    "slug": "dog-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "families",
      "classroom"
    ],
    "seed": "curated-dog-word-search-v1",
    "words": [
      "PUPPY",
      "LEASH",
      "COLLAR",
      "KENNEL",
      "TREAT",
      "FETCH",
      "BARK",
      "PAWS",
      "TAIL",
      "WHISKERS",
      "WALK",
      "TRAINING"
    ],
    "introduction": "Find familiar words connected with dogs, from everyday walks and training to the features that make each dog recognizable.",
    "context": "The puzzle mixes dog-care vocabulary with common actions and physical features, making it suitable for a short printable activity or an introductory animal theme.",
    "difficultyNote": "This easy puzzle uses a compact grid and forward directions only.",
    "metaTitle": "Dog Word Search | Free Printable and Online Puzzle",
    "metaDescription": "Find dog-themed words in this free word search. Play online, print the puzzle, download a PDF, or use the included answer key."
  },
  {
    "order": 2,
    "title": "Cat Word Search",
    "category": "Animals",
    "slug": "cat-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-cat-word-search-v1",
    "words": [
      "KITTEN",
      "WHISKERS",
      "PURR",
      "PAWS",
      "CLAWS",
      "NAP",
      "YARN",
      "LITTER",
      "TAIL",
      "MEOW",
      "CUSHION",
      "PLAYFUL"
    ],
    "introduction": "Search for words that describe cats, their sounds, their habits, and the objects commonly associated with them.",
    "context": "This cat puzzle focuses on recognizable household vocabulary rather than obscure breeds or specialist terminology.",
    "difficultyNote": "The forward-only paths make this a suitable starting puzzle.",
    "metaTitle": "Cat Word Search | Free Printable Puzzle with Answers",
    "metaDescription": "Play or print a free cat word search featuring familiar feline words. Download the PDF and check the matching answer key."
  },
  {
    "order": 3,
    "title": "Farm Animals Word Search",
    "category": "Animals",
    "slug": "farm-animals-word-search",
    "difficulty": "easy",
    "audience": [
      "Kids",
      "families",
      "classroom"
    ],
    "seed": "curated-farm-animals-word-search-v1",
    "words": [
      "HORSE",
      "COW",
      "SHEEP",
      "GOAT",
      "PIG",
      "CHICKEN",
      "DUCK",
      "DONKEY",
      "BARN",
      "PASTURE",
      "TRACTOR",
      "FARMER"
    ],
    "introduction": "Look for common farm animals along with a few words connected with the places and people found on a farm.",
    "context": "The vocabulary works well for animal units, farm themes, early readers, and printable classroom activity stations.",
    "difficultyNote": "The short word list and forward directions keep the puzzle approachable.",
    "metaTitle": "Farm Animals Word Search | Free Printable Worksheet",
    "metaDescription": "Print or play a farm animals word search with familiar animals and farm vocabulary. PDF and answer key options are included."
  },
  {
    "order": 4,
    "title": "Ocean Animals Word Search",
    "category": "Animals",
    "slug": "ocean-animals-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-ocean-animals-word-search-v1",
    "words": [
      "DOLPHIN",
      "WHALE",
      "SHARK",
      "OCTOPUS",
      "SEAL",
      "TURTLE",
      "JELLYFISH",
      "SEAHORSE",
      "STINGRAY",
      "LOBSTER",
      "CRAB",
      "SQUID",
      "CORAL",
      "STARFISH",
      "ORCA",
      "MANATEE"
    ],
    "introduction": "Explore ocean vocabulary by finding marine animals that live near shorelines, reefs, and open water.",
    "context": "The list includes mammals, fish, reptiles, crustaceans, and other sea life, giving the puzzle broader variety than a basic ocean list.",
    "difficultyNote": "Words may appear forwards, backwards, vertically, horizontally, or diagonally.",
    "metaTitle": "Ocean Animals Word Search | Printable PDF and Online",
    "metaDescription": "Find dolphins, whales, sharks, and more in this ocean animals word search. Play online or print the PDF with an answer key."
  },
  {
    "order": 5,
    "title": "Zoo Animals Word Search",
    "category": "Animals",
    "slug": "zoo-animals-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-zoo-animals-word-search-v1",
    "words": [
      "LION",
      "TIGER",
      "ELEPHANT",
      "GIRAFFE",
      "ZEBRA",
      "GORILLA",
      "PANDA",
      "RHINO",
      "HIPPO",
      "CHEETAH",
      "MEERKAT",
      "FLAMINGO",
      "KANGAROO",
      "CAMEL",
      "LEMUR",
      "OTTER"
    ],
    "introduction": "Find animals commonly seen in zoo exhibits, including large mammals, birds, and smaller social species.",
    "context": "This puzzle provides a broad animal vocabulary list without relying on fictional characters or branded attractions.",
    "difficultyNote": "Sixteen words and backwards directions create a moderate challenge.",
    "metaTitle": "Zoo Animals Word Search | Free Printable Puzzle",
    "metaDescription": "Play or print a zoo animals word search with lions, elephants, pandas, giraffes, and more. Includes a PDF and answer key."
  },
  {
    "order": 6,
    "title": "Birds Word Search",
    "category": "Animals",
    "slug": "birds-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-birds-word-search-v1",
    "words": [
      "ROBIN",
      "EAGLE",
      "OWL",
      "SPARROW",
      "CARDINAL",
      "FALCON",
      "PARROT",
      "PENGUIN",
      "SWAN",
      "HERON",
      "PELICAN",
      "FINCH",
      "RAVEN",
      "HAWK",
      "PUFFIN",
      "WOODPECKER"
    ],
    "introduction": "Search for familiar birds ranging from backyard visitors to seabirds and birds of prey.",
    "context": "The vocabulary spans different habitats and bird groups, making it useful for nature themes and general animal study.",
    "difficultyNote": "Longer names and mixed directions create a medium-level puzzle.",
    "metaTitle": "Birds Word Search | Free Printable and Online Puzzle",
    "metaDescription": "Find robins, owls, eagles, penguins, and other birds. Play this word search online or print the PDF with answers."
  },
  {
    "order": 7,
    "title": "Insects Word Search",
    "category": "Animals",
    "slug": "insects-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-insects-word-search-v1",
    "words": [
      "ANT",
      "BEE",
      "BEETLE",
      "BUTTERFLY",
      "MOTH",
      "DRAGONFLY",
      "GRASSHOPPER",
      "LADYBUG",
      "MOSQUITO",
      "CRICKET",
      "TERMITE",
      "FIREFLY",
      "CICADA",
      "MANTIS",
      "FLEA",
      "WASP"
    ],
    "introduction": "Find insect names that include pollinators, garden visitors, nighttime insects, and social colonies.",
    "context": "The mix of short and long words gives the puzzle varied visual patterns while keeping the theme clear.",
    "difficultyNote": "Backwards and diagonal placements make this more challenging than an introductory insect activity.",
    "metaTitle": "Insects Word Search | Printable Science Puzzle",
    "metaDescription": "Search for butterflies, beetles, bees, dragonflies, and more. Print the insect word search or play online with answers."
  },
  {
    "order": 8,
    "title": "Reptiles Word Search",
    "category": "Animals",
    "slug": "reptiles-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-reptiles-word-search-v1",
    "words": [
      "SNAKE",
      "LIZARD",
      "TURTLE",
      "TORTOISE",
      "CROCODILE",
      "ALLIGATOR",
      "GECKO",
      "IGUANA",
      "CHAMELEON",
      "COBRA",
      "PYTHON",
      "SKINK",
      "ANOLE",
      "VIPER",
      "CAIMAN",
      "MONITOR"
    ],
    "introduction": "Look for reptile names covering snakes, lizards, turtles, and large aquatic reptiles.",
    "context": "The word list combines familiar reptiles with several less obvious examples, adding useful vocabulary without becoming overly technical.",
    "difficultyNote": "The longer animal names and eight possible directions create a medium challenge.",
    "metaTitle": "Reptiles Word Search | Free Printable PDF",
    "metaDescription": "Find snakes, turtles, geckos, crocodiles, and other reptiles. Play online or print this free word search with an answer key."
  },
  {
    "order": 9,
    "title": "Fruits Word Search",
    "category": "Food",
    "slug": "fruits-word-search",
    "difficulty": "easy",
    "audience": [
      "Kids",
      "families",
      "ESL"
    ],
    "seed": "curated-fruits-word-search-v1",
    "words": [
      "APPLE",
      "BANANA",
      "ORANGE",
      "GRAPE",
      "PEACH",
      "PEAR",
      "MANGO",
      "CHERRY",
      "MELON",
      "LEMON",
      "PLUM",
      "KIWI"
    ],
    "introduction": "Find twelve familiar fruits in a compact puzzle designed for quick solving and vocabulary practice.",
    "context": "The list uses common fruit names that are suitable for younger readers, ESL activities, and food-themed printables.",
    "difficultyNote": "Short words and forward directions keep this puzzle easy to scan.",
    "metaTitle": "Fruits Word Search | Easy Free Printable Puzzle",
    "metaDescription": "Find apples, bananas, grapes, mangoes, and more in this easy fruit word search. Play online or print the PDF with answers."
  },
  {
    "order": 10,
    "title": "Vegetables Word Search",
    "category": "Food",
    "slug": "vegetables-word-search",
    "difficulty": "easy",
    "audience": [
      "Kids",
      "families",
      "ESL"
    ],
    "seed": "curated-vegetables-word-search-v1",
    "words": [
      "CARROT",
      "POTATO",
      "ONION",
      "CELERY",
      "CABBAGE",
      "PEPPER",
      "CORN",
      "PEA",
      "BEAN",
      "RADISH",
      "SPINACH",
      "SQUASH"
    ],
    "introduction": "Search for common vegetables found in gardens, grocery stores, and everyday meals.",
    "context": "This puzzle supports basic food vocabulary with a balanced list of roots, greens, and other familiar vegetables.",
    "difficultyNote": "The grid uses forward-only paths and a manageable twelve-word list.",
    "metaTitle": "Vegetables Word Search | Free Printable for Kids",
    "metaDescription": "Play or print an easy vegetables word search with carrots, potatoes, spinach, corn, and more. Includes a PDF answer key."
  },
  {
    "order": 11,
    "title": "Breakfast Word Search",
    "category": "Food",
    "slug": "breakfast-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "ESL"
    ],
    "seed": "curated-breakfast-word-search-v1",
    "words": [
      "PANCAKE",
      "WAFFLE",
      "CEREAL",
      "TOAST",
      "OATMEAL",
      "YOGURT",
      "BACON",
      "EGGS",
      "MUFFIN",
      "BAGEL",
      "COFFEE",
      "JUICE",
      "BERRIES",
      "SYRUP",
      "OMELET",
      "GRANOLA"
    ],
    "introduction": "Find breakfast foods and drinks that might appear in a quick weekday meal or a larger weekend breakfast.",
    "context": "The vocabulary includes grains, fruit, baked foods, drinks, and cooked dishes rather than repeating one type of breakfast item.",
    "difficultyNote": "Sixteen words and mixed directions make this a moderate puzzle.",
    "metaTitle": "Breakfast Word Search | Free Printable Food Puzzle",
    "metaDescription": "Find pancakes, waffles, cereal, toast, fruit, and more in this breakfast word search. Play online or print with answers."
  },
  {
    "order": 12,
    "title": "Baking Word Search",
    "category": "Food",
    "slug": "baking-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-baking-word-search-v1",
    "words": [
      "FLOUR",
      "SUGAR",
      "BUTTER",
      "YEAST",
      "DOUGH",
      "WHISK",
      "MIXER",
      "OVEN",
      "RECIPE",
      "APRON",
      "SPATULA",
      "MEASURE",
      "KNEAD",
      "FROSTING",
      "BATTER",
      "ROLLING"
    ],
    "introduction": "Search for ingredients, tools, and actions used when preparing baked goods.",
    "context": "This puzzle includes practical kitchen vocabulary such as measuring, mixing, kneading, and using common baking equipment.",
    "difficultyNote": "Longer process words and backwards placements provide a medium challenge.",
    "metaTitle": "Baking Word Search | Printable Kitchen Vocabulary",
    "metaDescription": "Find baking tools, ingredients, and actions in this free word search. Play online or download the printable PDF and key."
  },
  {
    "order": 13,
    "title": "Desserts Word Search",
    "category": "Food",
    "slug": "desserts-word-search",
    "difficulty": "medium",
    "audience": [
      "General"
    ],
    "seed": "curated-desserts-word-search-v1",
    "words": [
      "COOKIE",
      "BROWNIE",
      "CUPCAKE",
      "PUDDING",
      "CHEESECAKE",
      "DONUT",
      "CUSTARD",
      "TRIFLE",
      "TART",
      "ECLAIR",
      "SUNDAE",
      "GELATO",
      "COBBLER",
      "MOUSSE",
      "MACARON",
      "PARFAIT"
    ],
    "introduction": "Find baked, chilled, layered, and frozen desserts hidden throughout the grid.",
    "context": "The list includes familiar treats alongside several classic dessert styles, giving the page more variety than a basic sweets list.",
    "difficultyNote": "The mixture of long and short words creates a medium-level search.",
    "metaTitle": "Desserts Word Search | Free Printable and Online",
    "metaDescription": "Find cookies, brownies, cupcakes, gelato, tarts, and more. Play the dessert word search online or print the PDF with answers."
  },
  {
    "order": 14,
    "title": "Ice Cream Word Search",
    "category": "Food",
    "slug": "ice-cream-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-ice-cream-word-search-v1",
    "words": [
      "VANILLA",
      "CHOCOLATE",
      "STRAWBERRY",
      "CONE",
      "SCOOP",
      "SPRINKLES",
      "SUNDAE",
      "CARAMEL",
      "CHERRY",
      "FREEZER",
      "WAFFLE",
      "TOPPING"
    ],
    "introduction": "Search for flavors, toppings, serving styles, and other words connected with ice cream.",
    "context": "The vocabulary stays generic and product-focused without relying on branded flavors or commercial names.",
    "difficultyNote": "Forward directions and twelve words make this a quick printable puzzle.",
    "metaTitle": "Ice Cream Word Search | Easy Printable Puzzle",
    "metaDescription": "Find ice cream flavors, cones, scoops, toppings, and sundaes. Play online or print this easy word search with answers."
  },
  {
    "order": 15,
    "title": "Flowers Word Search",
    "category": "Nature",
    "slug": "flowers-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-flowers-word-search-v1",
    "words": [
      "ROSE",
      "TULIP",
      "DAISY",
      "LILY",
      "IRIS",
      "VIOLET",
      "POPPY",
      "ORCHID",
      "PETAL",
      "STEM",
      "BLOOM",
      "GARDEN"
    ],
    "introduction": "Find familiar flower names along with a few basic words describing how flowers grow and appear.",
    "context": "This compact nature puzzle is suitable for spring activities, garden themes, and introductory plant vocabulary.",
    "difficultyNote": "The short list and forward paths make the puzzle easy to complete.",
    "metaTitle": "Flowers Word Search | Free Printable Nature Puzzle",
    "metaDescription": "Find roses, tulips, daisies, lilies, petals, and more. Play this flower word search online or print it with an answer key."
  },
  {
    "order": 16,
    "title": "Trees Word Search",
    "category": "Nature",
    "slug": "trees-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-trees-word-search-v1",
    "words": [
      "MAPLE",
      "OAK",
      "PINE",
      "BIRCH",
      "CEDAR",
      "WILLOW",
      "ELM",
      "SPRUCE",
      "REDWOOD",
      "ASPEN",
      "CYPRESS",
      "PALM",
      "BARK",
      "ROOTS",
      "BRANCH",
      "CANOPY"
    ],
    "introduction": "Search for tree species and structural words connected with trunks, branches, roots, and forest canopies.",
    "context": "The list combines recognizable trees with general tree vocabulary, making it useful beyond simple species identification.",
    "difficultyNote": "Sixteen terms and mixed directions provide a moderate nature puzzle.",
    "metaTitle": "Trees Word Search | Printable Nature Vocabulary",
    "metaDescription": "Find maple, oak, pine, cedar, redwood, roots, branches, and more. Print the tree word search or play online with answers."
  },
  {
    "order": 17,
    "title": "Garden Word Search",
    "category": "Nature",
    "slug": "garden-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "adults",
      "classroom"
    ],
    "seed": "curated-garden-word-search-v1",
    "words": [
      "SEEDS",
      "SOIL",
      "SHOVEL",
      "RAKE",
      "WATERING",
      "COMPOST",
      "MULCH",
      "SPROUT",
      "WEEDS",
      "HARVEST",
      "PLANTER",
      "TROWEL",
      "GREENHOUSE",
      "FLOWERS",
      "VEGETABLES",
      "SUNLIGHT"
    ],
    "introduction": "Find tools, materials, growing conditions, and activities connected with maintaining a garden.",
    "context": "The vocabulary covers the full gardening process, from planting seeds and preparing soil to watering and harvesting.",
    "difficultyNote": "Several longer words and reverse directions create a medium challenge.",
    "metaTitle": "Garden Word Search | Free Printable Puzzle",
    "metaDescription": "Search for garden tools, seeds, soil, compost, flowers, and more. Play online or print this gardening word search with answers."
  },
  {
    "order": 18,
    "title": "Forest Word Search",
    "category": "Nature",
    "slug": "forest-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-forest-word-search-v1",
    "words": [
      "TREES",
      "MOSS",
      "FERN",
      "TRAIL",
      "CANOPY",
      "WILDLIFE",
      "STREAM",
      "LOG",
      "ACORN",
      "SHADE",
      "CLEARING",
      "HABITAT",
      "WOODLAND",
      "SAPLING",
      "UNDERGROWTH",
      "EVERGREEN"
    ],
    "introduction": "Search for plants, landscape features, and habitat words associated with forests and woodland trails.",
    "context": "The word list describes both what visitors may observe and how a forest environment is structured.",
    "difficultyNote": "Longer habitat terms make this a medium-level puzzle.",
    "metaTitle": "Forest Word Search | Free Printable Nature Activity",
    "metaDescription": "Find trees, moss, trails, wildlife, streams, and woodland vocabulary. Play online or print the forest word search and key."
  },
  {
    "order": 19,
    "title": "Beach Word Search",
    "category": "Nature",
    "slug": "beach-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-beach-word-search-v1",
    "words": [
      "SAND",
      "WAVES",
      "SHELL",
      "OCEAN",
      "TOWEL",
      "UMBRELLA",
      "SURF",
      "SUNSCREEN",
      "BUCKET",
      "CASTLE",
      "BOARDWALK",
      "SEAGULL"
    ],
    "introduction": "Find seaside words connected with sand, waves, beach equipment, and familiar shoreline sights.",
    "context": "This easy puzzle works as a summer printable without depending on a particular resort, brand, or destination.",
    "difficultyNote": "Twelve forward-only words keep the activity quick and accessible.",
    "metaTitle": "Beach Word Search | Easy Summer Printable",
    "metaDescription": "Find sand, waves, shells, umbrellas, surf, and more in this easy beach word search. Play online or print the PDF with answers."
  },
  {
    "order": 20,
    "title": "Weather Word Search",
    "category": "Nature",
    "slug": "weather-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "general"
    ],
    "seed": "curated-weather-word-search-v1",
    "words": [
      "SUNNY",
      "CLOUDY",
      "RAIN",
      "SNOW",
      "WIND",
      "THUNDER",
      "LIGHTNING",
      "FORECAST",
      "TEMPERATURE",
      "HUMIDITY",
      "STORM",
      "BREEZE",
      "FOG",
      "HAIL",
      "TORNADO",
      "RAINBOW"
    ],
    "introduction": "Search for weather conditions, measurements, and events commonly discussed in forecasts.",
    "context": "The puzzle moves beyond basic weather words by including temperature, humidity, forecasting, and severe-weather vocabulary.",
    "difficultyNote": "Sixteen terms and all eight directions make this a medium challenge.",
    "metaTitle": "Weather Word Search | Printable Science Worksheet",
    "metaDescription": "Find rain, snow, wind, storms, forecasts, temperature, and more. Play the weather word search or print it with answers."
  },
  {
    "order": 21,
    "title": "Space Word Search",
    "category": "Science",
    "slug": "space-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "general"
    ],
    "seed": "curated-space-word-search-v1",
    "words": [
      "ASTRONAUT",
      "ROCKET",
      "PLANET",
      "GALAXY",
      "COMET",
      "ASTEROID",
      "ORBIT",
      "SATELLITE",
      "TELESCOPE",
      "NEBULA",
      "STAR",
      "MOON",
      "GRAVITY",
      "UNIVERSE",
      "LAUNCH",
      "SPACECRAFT"
    ],
    "introduction": "Find words connected with space exploration, astronomical objects, and the technology used to study the universe.",
    "context": "The list combines scientific vocabulary with familiar exploration terms, making it useful for general space themes and classroom review.",
    "difficultyNote": "Longer words and reverse directions produce a medium-level puzzle.",
    "metaTitle": "Space Word Search | Free Printable Science Puzzle",
    "metaDescription": "Find astronauts, rockets, planets, galaxies, comets, and more. Play online or print this space word search with an answer key."
  },
  {
    "order": 22,
    "title": "Solar System Word Search",
    "category": "Science",
    "slug": "solar-system-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom"
    ],
    "seed": "curated-solar-system-word-search-v1",
    "words": [
      "MERCURY",
      "VENUS",
      "EARTH",
      "MARS",
      "JUPITER",
      "SATURN",
      "URANUS",
      "NEPTUNE",
      "SUN",
      "MOON",
      "ORBIT",
      "PLANET",
      "ASTEROID",
      "COMET",
      "GRAVITY",
      "TELESCOPE"
    ],
    "introduction": "Search for the eight planets and other important solar-system terms.",
    "context": "The puzzle keeps the planetary names together while adding the Sun, Moon, orbit, gravity, and smaller objects found in the same system.",
    "difficultyNote": "Mixed directions and several long planet names create a medium challenge.",
    "metaTitle": "Solar System Word Search | Printable with Answers",
    "metaDescription": "Find all eight planets plus the Sun, Moon, comets, and more. Print or play this solar system word search with an answer key."
  },
  {
    "order": 23,
    "title": "Biology Word Search",
    "category": "Science",
    "slug": "biology-word-search",
    "difficulty": "hard",
    "audience": [
      "Middle school",
      "high school",
      "adults"
    ],
    "seed": "curated-biology-word-search-v1",
    "words": [
      "CELL",
      "NUCLEUS",
      "MEMBRANE",
      "CYTOPLASM",
      "ORGANISM",
      "TISSUE",
      "ORGAN",
      "GENETICS",
      "DNA",
      "SPECIES",
      "HABITAT",
      "ECOSYSTEM",
      "EVOLUTION",
      "PHOTOSYNTHESIS",
      "RESPIRATION",
      "CHROMOSOME",
      "MITOSIS",
      "BACTERIA",
      "PROTEIN",
      "ENZYME"
    ],
    "introduction": "Find foundational biology vocabulary covering cells, genetics, organisms, and ecosystems.",
    "context": "The list spans several major biology units, making the puzzle appropriate as a broad review rather than a narrow single-lesson worksheet.",
    "difficultyNote": "Twenty terms, long scientific words, and all eight directions make this a hard puzzle.",
    "metaTitle": "Biology Word Search | Printable Science Worksheet",
    "metaDescription": "Review cells, genetics, ecosystems, photosynthesis, DNA, and more with this biology word search. PDF and answer key included."
  },
  {
    "order": 24,
    "title": "Chemistry Word Search",
    "category": "Science",
    "slug": "chemistry-word-search",
    "difficulty": "hard",
    "audience": [
      "Middle school",
      "high school",
      "adults"
    ],
    "seed": "curated-chemistry-word-search-v1",
    "words": [
      "ATOM",
      "MOLECULE",
      "ELEMENT",
      "COMPOUND",
      "REACTION",
      "SOLUTION",
      "SOLVENT",
      "SOLUTE",
      "ACID",
      "BASE",
      "PERIODIC",
      "ELECTRON",
      "PROTON",
      "NEUTRON",
      "BOND",
      "CATALYST",
      "DENSITY",
      "MASS",
      "VOLUME",
      "LABORATORY"
    ],
    "introduction": "Search for chemistry terms describing matter, particles, solutions, reactions, and laboratory work.",
    "context": "The vocabulary provides a broad foundation for introductory chemistry review without focusing on one specific textbook or curriculum.",
    "difficultyNote": "Twenty scientific terms and dense mixed-direction placement make this a hard puzzle.",
    "metaTitle": "Chemistry Word Search | Printable Worksheet and Key",
    "metaDescription": "Find atoms, molecules, elements, reactions, acids, bases, and more. Print or play this chemistry word search with answers."
  },
  {
    "order": 25,
    "title": "Physics Word Search",
    "category": "Science",
    "slug": "physics-word-search",
    "difficulty": "hard",
    "audience": [
      "Middle school",
      "high school",
      "adults"
    ],
    "seed": "curated-physics-word-search-v1",
    "words": [
      "FORCE",
      "MOTION",
      "ENERGY",
      "MASS",
      "VELOCITY",
      "GRAVITY",
      "FRICTION",
      "MOMENTUM",
      "ACCELERATION",
      "WAVE",
      "FREQUENCY",
      "VOLTAGE",
      "CURRENT",
      "RESISTANCE",
      "MAGNETISM",
      "PRESSURE",
      "POWER",
      "WORK",
      "LIGHT",
      "SOUND"
    ],
    "introduction": "Find physics vocabulary covering motion, forces, energy, waves, electricity, and other introductory concepts.",
    "context": "The list connects several major physics areas in one general review puzzle rather than limiting the page to a single formula or unit.",
    "difficultyNote": "Twenty terms and long diagonal or reverse placements create a hard challenge.",
    "metaTitle": "Physics Word Search | Free Printable Science Review",
    "metaDescription": "Review force, motion, energy, gravity, waves, electricity, and more with this printable physics word search and answer key."
  },
  {
    "order": 26,
    "title": "Geology Word Search",
    "category": "Science",
    "slug": "geology-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "general"
    ],
    "seed": "curated-geology-word-search-v1",
    "words": [
      "ROCK",
      "MINERAL",
      "CRYSTAL",
      "MAGMA",
      "LAVA",
      "VOLCANO",
      "EARTHQUAKE",
      "FOSSIL",
      "SEDIMENT",
      "EROSION",
      "MANTLE",
      "CRUST",
      "FAULT",
      "GRANITE",
      "MARBLE",
      "LIMESTONE"
    ],
    "introduction": "Search for words describing rocks, minerals, Earth’s layers, and geological processes.",
    "context": "The vocabulary balances materials such as granite and limestone with processes such as erosion, earthquakes, and volcanic activity.",
    "difficultyNote": "Sixteen terms and mixed directions create a moderate Earth-science puzzle.",
    "metaTitle": "Geology Word Search | Printable Earth Science Puzzle",
    "metaDescription": "Find rocks, minerals, fossils, volcanoes, earthquakes, and more. Play or print this geology word search with an answer key."
  },
  {
    "order": 27,
    "title": "Continents Word Search",
    "category": "Geography",
    "slug": "continents-word-search",
    "difficulty": "easy",
    "audience": [
      "Classroom",
      "families"
    ],
    "seed": "curated-continents-word-search-v1",
    "words": [
      "AFRICA",
      "ANTARCTICA",
      "ASIA",
      "EUROPE",
      "AUSTRALIA",
      "NORTHAMERICA",
      "SOUTHAMERICA",
      "MAP",
      "GLOBE",
      "EQUATOR",
      "HEMISPHERE",
      "OCEAN"
    ],
    "introduction": "Find the seven continents along with a few basic world-map terms.",
    "context": "The puzzle keeps the main geographic names together and adds vocabulary used when locating continents on a globe or map.",
    "difficultyNote": "Forward directions keep the page accessible despite several long continent names.",
    "metaTitle": "Continents Word Search | Free Printable Geography",
    "metaDescription": "Find all seven continents plus map and globe vocabulary. Play online or print this geography word search with answers."
  },
  {
    "order": 28,
    "title": "Oceans Word Search",
    "category": "Geography",
    "slug": "oceans-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "general"
    ],
    "seed": "curated-oceans-word-search-v1",
    "words": [
      "PACIFIC",
      "ATLANTIC",
      "INDIAN",
      "ARCTIC",
      "SOUTHERN",
      "CURRENT",
      "TIDE",
      "WAVE",
      "COAST",
      "TRENCH",
      "REEF",
      "ISLAND",
      "HARBOR",
      "GULF",
      "BAY",
      "STRAIT"
    ],
    "introduction": "Search for the world’s oceans and physical features associated with coastlines and ocean water.",
    "context": "The list includes all five named oceans together with currents, tides, reefs, trenches, and coastal landforms.",
    "difficultyNote": "Long ocean names and reverse directions create a medium challenge.",
    "metaTitle": "Oceans Word Search | Printable Geography Puzzle",
    "metaDescription": "Find the Pacific, Atlantic, Indian, Arctic, and Southern oceans plus coastal vocabulary. Print or play with answers."
  },
  {
    "order": 29,
    "title": "World Capitals Word Search",
    "category": "Geography",
    "slug": "world-capitals-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "adults"
    ],
    "seed": "curated-world-capitals-word-search-v1",
    "words": [
      "LONDON",
      "PARIS",
      "ROME",
      "MADRID",
      "BERLIN",
      "OTTAWA",
      "TOKYO",
      "SEOUL",
      "CAIRO",
      "LIMA",
      "OSLO",
      "DUBLIN",
      "ATHENS",
      "VIENNA",
      "WARSAW",
      "PRAGUE"
    ],
    "introduction": "Find sixteen national capitals from Europe, Asia, Africa, and the Americas.",
    "context": "The selection provides recognizable capitals from several regions without claiming to be a complete world-capital list.",
    "difficultyNote": "Mixed directions and similar letter patterns create a medium geography challenge.",
    "metaTitle": "World Capitals Word Search | Printable Geography",
    "metaDescription": "Find London, Paris, Tokyo, Ottawa, Cairo, Lima, and other world capitals. Play online or print the puzzle and answer key."
  },
  {
    "order": 30,
    "title": "US States Word Search",
    "category": "Geography",
    "slug": "us-states-word-search",
    "difficulty": "hard",
    "audience": [
      "Classroom",
      "adults"
    ],
    "seed": "curated-us-states-word-search-v1",
    "words": [
      "ALASKA",
      "ARIZONA",
      "CALIFORNIA",
      "COLORADO",
      "DELAWARE",
      "FLORIDA",
      "GEORGIA",
      "HAWAII",
      "IDAHO",
      "ILLINOIS",
      "INDIANA",
      "IOWA",
      "KANSAS",
      "KENTUCKY",
      "MAINE",
      "MARYLAND",
      "MICHIGAN",
      "MONTANA",
      "NEBRASKA",
      "NEVADA"
    ],
    "introduction": "Search for twenty US state names hidden across a larger grid.",
    "context": "This first state puzzle uses one-word state names so the vocabulary remains readable in both the grid and word bank.",
    "difficultyNote": "Twenty state names and all eight directions make this a hard puzzle.",
    "metaTitle": "US States Word Search | Printable Geography Puzzle",
    "metaDescription": "Find twenty US states in a challenging word search. Play online or print the PDF with a matching answer key."
  },
  {
    "order": 31,
    "title": "Canada Word Search",
    "category": "Geography",
    "slug": "canada-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "general"
    ],
    "seed": "curated-canada-word-search-v1",
    "words": [
      "CANADA",
      "ALBERTA",
      "ONTARIO",
      "QUEBEC",
      "MANITOBA",
      "SASKATCHEWAN",
      "NOVASCOTIA",
      "NUNAVUT",
      "YUKON",
      "OTTAWA",
      "MAPLE",
      "PRAIRIE",
      "ROCKIES",
      "ARCTIC",
      "PACIFIC",
      "ATLANTIC"
    ],
    "introduction": "Find Canadian provinces, territories, regions, and national geography vocabulary.",
    "context": "The list combines political geography with coastlines, landscapes, and the national capital for a broader Canada theme.",
    "difficultyNote": "Several long place names and backwards directions make this a medium challenge.",
    "metaTitle": "Canada Word Search | Free Printable Geography",
    "metaDescription": "Find Canadian provinces, territories, Ottawa, the Rockies, and more. Play the Canada word search online or print with answers."
  },
  {
    "order": 32,
    "title": "Map Vocabulary Word Search",
    "category": "Geography",
    "slug": "map-vocabulary-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom"
    ],
    "seed": "curated-map-vocabulary-word-search-v1",
    "words": [
      "COMPASS",
      "LEGEND",
      "SCALE",
      "BORDER",
      "REGION",
      "SYMBOL",
      "ROUTE",
      "NORTH",
      "SOUTH",
      "EAST",
      "WEST",
      "GRID",
      "LATITUDE",
      "LONGITUDE",
      "ATLAS",
      "GLOBE"
    ],
    "introduction": "Search for terms used to read maps, follow routes, and describe locations.",
    "context": "The vocabulary covers direction, map symbols, scale, coordinates, and common reference tools such as atlases and globes.",
    "difficultyNote": "Sixteen geographic terms and mixed directions make this a medium puzzle.",
    "metaTitle": "Map Vocabulary Word Search | Printable Worksheet",
    "metaDescription": "Review compass directions, legends, scale, latitude, longitude, and more with this printable map vocabulary word search."
  },
  {
    "order": 33,
    "title": "Nouns Word Search",
    "category": "Language Arts",
    "slug": "nouns-word-search",
    "difficulty": "easy",
    "audience": [
      "Elementary classroom",
      "ESL"
    ],
    "seed": "curated-nouns-word-search-v1",
    "words": [
      "PERSON",
      "PLACE",
      "ANIMAL",
      "OBJECT",
      "TEACHER",
      "SCHOOL",
      "CITY",
      "RIVER",
      "BOOK",
      "TABLE",
      "MUSIC",
      "FRIEND"
    ],
    "introduction": "Find examples of nouns representing people, places, animals, objects, and ideas.",
    "context": "The puzzle supports introductory grammar practice by giving students concrete examples to classify after solving.",
    "difficultyNote": "The simple vocabulary and forward directions suit an introductory worksheet.",
    "metaTitle": "Nouns Word Search | Free Printable Grammar Worksheet",
    "metaDescription": "Find examples of people, places, animals, objects, and ideas in this easy nouns word search with a printable answer key."
  },
  {
    "order": 34,
    "title": "Verbs Word Search",
    "category": "Language Arts",
    "slug": "verbs-word-search",
    "difficulty": "easy",
    "audience": [
      "Elementary classroom",
      "ESL"
    ],
    "seed": "curated-verbs-word-search-v1",
    "words": [
      "RUN",
      "WALK",
      "READ",
      "WRITE",
      "SPEAK",
      "LISTEN",
      "THINK",
      "BUILD",
      "DRAW",
      "LAUGH",
      "CLIMB",
      "LEARN"
    ],
    "introduction": "Search for action words describing movement, communication, thinking, and everyday activities.",
    "context": "The selected verbs are common enough for early grammar practice while still offering different word lengths.",
    "difficultyNote": "Forward-only placement makes this a suitable beginner grammar puzzle.",
    "metaTitle": "Verbs Word Search | Easy Printable Grammar Puzzle",
    "metaDescription": "Find action words such as read, write, speak, climb, and learn. Print or play this verbs word search with answers."
  },
  {
    "order": 35,
    "title": "Adjectives Word Search",
    "category": "Language Arts",
    "slug": "adjectives-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "ESL"
    ],
    "seed": "curated-adjectives-word-search-v1",
    "words": [
      "BRIGHT",
      "QUIET",
      "TALL",
      "SHORT",
      "BRAVE",
      "GENTLE",
      "CURIOUS",
      "SMOOTH",
      "ROUGH",
      "WARM",
      "COLD",
      "CHEERFUL",
      "ANCIENT",
      "MODERN",
      "NARROW",
      "WIDE"
    ],
    "introduction": "Find describing words related to size, texture, temperature, mood, and age.",
    "context": "The vocabulary gives learners adjectives that can be compared, grouped, and used in follow-up sentences.",
    "difficultyNote": "Sixteen words and backwards directions make this a medium grammar puzzle.",
    "metaTitle": "Adjectives Word Search | Printable Grammar Worksheet",
    "metaDescription": "Find describing words for size, texture, temperature, mood, and more. Print or play the adjectives word search with answers."
  },
  {
    "order": 36,
    "title": "Synonyms Word Search",
    "category": "Language Arts",
    "slug": "synonyms-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom"
    ],
    "seed": "curated-synonyms-word-search-v1",
    "words": [
      "HAPPY",
      "JOYFUL",
      "QUICK",
      "RAPID",
      "SMALL",
      "TINY",
      "LARGE",
      "HUGE",
      "SMART",
      "CLEVER",
      "QUIET",
      "SILENT",
      "BEGIN",
      "START",
      "FINISH",
      "END"
    ],
    "introduction": "Search for eight pairs of words that have similar meanings.",
    "context": "The word bank can be used after solving to match each synonym pair and discuss differences in usage.",
    "difficultyNote": "The similar word pairs and mixed directions create a medium challenge.",
    "metaTitle": "Synonyms Word Search | Free Printable Vocabulary",
    "metaDescription": "Find and match synonym pairs such as happy and joyful, quick and rapid, and small and tiny in this printable word search."
  },
  {
    "order": 37,
    "title": "Antonyms Word Search",
    "category": "Language Arts",
    "slug": "antonyms-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "ESL"
    ],
    "seed": "curated-antonyms-word-search-v1",
    "words": [
      "HOT",
      "COLD",
      "HIGH",
      "LOW",
      "EARLY",
      "LATE",
      "LIGHT",
      "DARK",
      "FAST",
      "SLOW",
      "OPEN",
      "CLOSED",
      "NEAR",
      "FAR",
      "STRONG",
      "WEAK"
    ],
    "introduction": "Find eight pairs of opposite words hidden across the grid.",
    "context": "The completed word bank can support a follow-up matching exercise or sentence-writing activity using contrasting meanings.",
    "difficultyNote": "Mixed directions make the familiar vocabulary moderately challenging.",
    "metaTitle": "Antonyms Word Search | Printable Opposites Worksheet",
    "metaDescription": "Find opposite word pairs such as hot and cold, fast and slow, and strong and weak. Includes printable and answer-key options."
  },
  {
    "order": 38,
    "title": "Punctuation Word Search",
    "category": "Language Arts",
    "slug": "punctuation-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom"
    ],
    "seed": "curated-punctuation-word-search-v1",
    "words": [
      "PERIOD",
      "COMMA",
      "COLON",
      "SEMICOLON",
      "APOSTROPHE",
      "QUOTATION",
      "QUESTION",
      "EXCLAMATION",
      "HYPHEN",
      "DASH",
      "PARENTHESES",
      "BRACKETS",
      "ELLIPSIS",
      "SENTENCE",
      "CLAUSE",
      "GRAMMAR"
    ],
    "introduction": "Search for punctuation marks and related writing terms used to organize sentences.",
    "context": "Because punctuation symbols cannot function as ordinary placed words, the puzzle uses their written names and associated grammar vocabulary.",
    "difficultyNote": "Long terms such as parentheses and exclamation create a medium challenge.",
    "metaTitle": "Punctuation Word Search | Printable Grammar Review",
    "metaDescription": "Review commas, periods, quotation marks, apostrophes, parentheses, and more with this printable punctuation word search."
  },
  {
    "order": 39,
    "title": "Addition Word Search",
    "category": "Math",
    "slug": "addition-word-search",
    "difficulty": "easy",
    "audience": [
      "Elementary classroom"
    ],
    "seed": "curated-addition-word-search-v1",
    "words": [
      "ADD",
      "PLUS",
      "SUM",
      "TOTAL",
      "NUMBER",
      "COUNT",
      "EQUAL",
      "ONES",
      "TENS",
      "PAIR",
      "GROUP",
      "COMBINE"
    ],
    "introduction": "Find basic addition vocabulary used when combining numbers and describing sums.",
    "context": "The puzzle is designed as a light math-language activity rather than a replacement for calculation practice.",
    "difficultyNote": "Short terms and forward directions make this an easy worksheet.",
    "metaTitle": "Addition Word Search | Easy Printable Math Worksheet",
    "metaDescription": "Find addition words such as plus, sum, total, equal, and combine in this easy printable math word search with answers."
  },
  {
    "order": 40,
    "title": "Subtraction Word Search",
    "category": "Math",
    "slug": "subtraction-word-search",
    "difficulty": "easy",
    "audience": [
      "Elementary classroom"
    ],
    "seed": "curated-subtraction-word-search-v1",
    "words": [
      "SUBTRACT",
      "MINUS",
      "DIFFERENCE",
      "TAKEAWAY",
      "NUMBER",
      "EQUAL",
      "LESS",
      "LEFT",
      "DECREASE",
      "COUNT",
      "ONES",
      "TENS"
    ],
    "introduction": "Search for words commonly used when taking away, comparing quantities, and finding a difference.",
    "context": "The vocabulary reinforces the language of subtraction without presenting the puzzle as a calculation exercise.",
    "difficultyNote": "Forward placement balances several longer math terms.",
    "metaTitle": "Subtraction Word Search | Printable Math Vocabulary",
    "metaDescription": "Find subtraction words such as minus, difference, take away, less, and decrease. Print or play with an answer key."
  },
  {
    "order": 41,
    "title": "Multiplication Word Search",
    "category": "Math",
    "slug": "multiplication-word-search",
    "difficulty": "medium",
    "audience": [
      "Elementary",
      "middle school"
    ],
    "seed": "curated-multiplication-word-search-v1",
    "words": [
      "MULTIPLY",
      "PRODUCT",
      "FACTOR",
      "TIMES",
      "GROUPS",
      "ARRAY",
      "REPEATED",
      "EQUATION",
      "TABLE",
      "DOUBLE",
      "TRIPLE",
      "COMMUTATIVE",
      "NUMBER",
      "EQUAL",
      "PATTERN",
      "SKIPCOUNT"
    ],
    "introduction": "Find vocabulary used to describe multiplication, equal groups, arrays, and number patterns.",
    "context": "The list connects multiplication facts with visual and language-based concepts students encounter in classroom lessons.",
    "difficultyNote": "Longer terms and all eight directions create a medium puzzle.",
    "metaTitle": "Multiplication Word Search | Printable Math Worksheet",
    "metaDescription": "Review factors, products, arrays, times tables, and equal groups with this multiplication word search and answer key."
  },
  {
    "order": 42,
    "title": "Division Word Search",
    "category": "Math",
    "slug": "division-word-search",
    "difficulty": "medium",
    "audience": [
      "Elementary",
      "middle school"
    ],
    "seed": "curated-division-word-search-v1",
    "words": [
      "DIVIDE",
      "QUOTIENT",
      "DIVISOR",
      "DIVIDEND",
      "REMAINDER",
      "EQUAL",
      "GROUPS",
      "SHARE",
      "SPLIT",
      "FACTOR",
      "MULTIPLE",
      "EQUATION",
      "FRACTION",
      "NUMBER",
      "EVEN",
      "ODD"
    ],
    "introduction": "Search for division terms connected with sharing, grouping, quotients, and remainders.",
    "context": "The vocabulary can support a review of the language students encounter in division examples and word problems.",
    "difficultyNote": "Several specialist terms and reverse directions produce a medium challenge.",
    "metaTitle": "Division Word Search | Printable Math Vocabulary",
    "metaDescription": "Find quotient, divisor, dividend, remainder, groups, and more in this printable division word search with answers."
  },
  {
    "order": 43,
    "title": "Fractions Word Search",
    "category": "Math",
    "slug": "fractions-word-search",
    "difficulty": "medium",
    "audience": [
      "Elementary",
      "middle school"
    ],
    "seed": "curated-fractions-word-search-v1",
    "words": [
      "FRACTION",
      "NUMERATOR",
      "DENOMINATOR",
      "EQUIVALENT",
      "PROPER",
      "IMPROPER",
      "MIXED",
      "HALF",
      "THIRD",
      "QUARTER",
      "WHOLE",
      "PART",
      "SIMPLIFY",
      "COMPARE",
      "DECIMAL",
      "PERCENT"
    ],
    "introduction": "Find fraction vocabulary describing parts of a whole, fraction forms, and related number representations.",
    "context": "The list includes numerator and denominator along with equivalent fractions, mixed numbers, decimals, and percentages.",
    "difficultyNote": "Long mathematical words and mixed directions make this a medium challenge.",
    "metaTitle": "Fractions Word Search | Printable Math Review",
    "metaDescription": "Review numerator, denominator, equivalent fractions, mixed numbers, decimals, and more with this printable word search."
  },
  {
    "order": 44,
    "title": "Geometry Word Search",
    "category": "Math",
    "slug": "geometry-word-search",
    "difficulty": "medium",
    "audience": [
      "Elementary",
      "middle school"
    ],
    "seed": "curated-geometry-word-search-v1",
    "words": [
      "POINT",
      "LINE",
      "ANGLE",
      "SHAPE",
      "CIRCLE",
      "TRIANGLE",
      "SQUARE",
      "RECTANGLE",
      "POLYGON",
      "PERIMETER",
      "AREA",
      "VOLUME",
      "PARALLEL",
      "VERTEX",
      "SYMMETRY",
      "DIAMETER"
    ],
    "introduction": "Search for geometry vocabulary covering shapes, measurements, lines, angles, and symmetry.",
    "context": "The puzzle brings together foundational terms used across several introductory geometry units.",
    "difficultyNote": "Sixteen terms and diagonal or reverse placement create a medium challenge.",
    "metaTitle": "Geometry Word Search | Free Printable Math Puzzle",
    "metaDescription": "Find shapes, angles, perimeter, area, symmetry, vertices, and more. Play or print this geometry word search with answers."
  },
  {
    "order": 45,
    "title": "Soccer Word Search",
    "category": "Sports",
    "slug": "soccer-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-soccer-word-search-v1",
    "words": [
      "SOCCER",
      "GOAL",
      "KEEPER",
      "STRIKER",
      "DEFENDER",
      "MIDFIELD",
      "PASS",
      "DRIBBLE",
      "TACKLE",
      "CORNER",
      "PENALTY",
      "REFEREE",
      "STADIUM",
      "TEAM",
      "MATCH",
      "CLEATS"
    ],
    "introduction": "Find soccer positions, skills, equipment, and match vocabulary.",
    "context": "The list covers both how the game is played and the roles seen across the field.",
    "difficultyNote": "Long position names and mixed directions create a medium sports puzzle.",
    "metaTitle": "Soccer Word Search | Free Printable Sports Puzzle",
    "metaDescription": "Find goals, keepers, defenders, passing, dribbling, and more. Play the soccer word search online or print with answers."
  },
  {
    "order": 46,
    "title": "Basketball Word Search",
    "category": "Sports",
    "slug": "basketball-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-basketball-word-search-v1",
    "words": [
      "BASKETBALL",
      "HOOP",
      "COURT",
      "DRIBBLE",
      "PASS",
      "REBOUND",
      "DEFENSE",
      "OFFENSE",
      "DUNK",
      "LAYUP",
      "FOUL",
      "FREE THROW",
      "BACKBOARD",
      "PLAYER",
      "COACH",
      "TEAM"
    ],
    "introduction": "Search for basketball skills, court features, scoring plays, and team vocabulary.",
    "context": "The words represent familiar parts of a basketball game without depending on professional teams or player names.",
    "difficultyNote": "Mixed directions and multiword display terms produce a medium challenge.",
    "metaTitle": "Basketball Word Search | Printable Sports Activity",
    "metaDescription": "Find hoops, dribbling, rebounds, layups, defense, and more. Play online or print this basketball word search and answer key."
  },
  {
    "order": 47,
    "title": "Baseball Word Search",
    "category": "Sports",
    "slug": "baseball-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-baseball-word-search-v1",
    "words": [
      "BASEBALL",
      "PITCHER",
      "CATCHER",
      "BATTER",
      "INFIELD",
      "OUTFIELD",
      "DUGOUT",
      "DIAMOND",
      "HOMERUN",
      "STRIKE",
      "BALL",
      "BASE",
      "GLOVE",
      "UMPIRE",
      "INNING",
      "SCORE"
    ],
    "introduction": "Find baseball positions, equipment, field areas, and game terms.",
    "context": "The puzzle uses general baseball vocabulary rather than league, team, or player names.",
    "difficultyNote": "Sixteen words and mixed directions create a medium sports puzzle.",
    "metaTitle": "Baseball Word Search | Free Printable Puzzle",
    "metaDescription": "Find pitchers, catchers, innings, home runs, gloves, and more. Play or print this baseball word search with an answer key."
  },
  {
    "order": 48,
    "title": "Hockey Word Search",
    "category": "Sports",
    "slug": "hockey-word-search",
    "difficulty": "medium",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-hockey-word-search-v1",
    "words": [
      "HOCKEY",
      "PUCK",
      "STICK",
      "SKATES",
      "GOALIE",
      "RINK",
      "ICE",
      "DEFENSE",
      "FORWARD",
      "FACEOFF",
      "PENALTY",
      "PERIOD",
      "SCORE",
      "HELMET",
      "BENCH",
      "REFEREE"
    ],
    "introduction": "Search for hockey equipment, positions, rink features, and game vocabulary.",
    "context": "The word list stays applicable to hockey generally and does not depend on any professional league or team.",
    "difficultyNote": "Longer terms and backwards paths make this a medium challenge.",
    "metaTitle": "Hockey Word Search | Free Printable Sports Puzzle",
    "metaDescription": "Find pucks, sticks, skates, goalies, faceoffs, penalties, and more. Play online or print this hockey word search with answers."
  },
  {
    "order": 49,
    "title": "School Supplies Word Search",
    "category": "Classroom",
    "slug": "school-supplies-word-search",
    "difficulty": "easy",
    "audience": [
      "Kids",
      "classroom",
      "ESL"
    ],
    "seed": "curated-school-supplies-word-search-v1",
    "words": [
      "PENCIL",
      "ERASER",
      "RULER",
      "PAPER",
      "MARKER",
      "CRAYON",
      "GLUE",
      "SCISSORS",
      "NOTEBOOK",
      "FOLDER",
      "BACKPACK",
      "SHARPENER"
    ],
    "introduction": "Find common school supplies used for writing, drawing, organizing, and classroom projects.",
    "context": "The familiar vocabulary makes this page suitable for younger students, ESL review, and back-to-school activity stations.",
    "difficultyNote": "Forward-only directions keep the puzzle accessible.",
    "metaTitle": "School Supplies Word Search | Free Printable",
    "metaDescription": "Find pencils, rulers, notebooks, backpacks, scissors, and more in this easy school supplies word search with answers."
  },
  {
    "order": 50,
    "title": "Classroom Word Search",
    "category": "Classroom",
    "slug": "classroom-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "teachers"
    ],
    "seed": "curated-classroom-word-search-v1",
    "words": [
      "TEACHER",
      "STUDENT",
      "DESK",
      "BOARD",
      "LESSON",
      "HOMEWORK",
      "PROJECT",
      "READING",
      "WRITING",
      "MATH",
      "SCIENCE",
      "LIBRARY",
      "COMPUTER",
      "QUESTION",
      "ANSWER",
      "RECESS"
    ],
    "introduction": "Search for people, places, subjects, and activities commonly found in a school day.",
    "context": "The broad classroom vocabulary makes the puzzle useful as a general school-themed worksheet rather than a single-subject resource.",
    "difficultyNote": "Sixteen words and mixed directions create a medium challenge.",
    "metaTitle": "Classroom Word Search | Printable School Worksheet",
    "metaDescription": "Find teacher, student, homework, reading, science, library, and more. Print or play this classroom word search with answers."
  },
  {
    "order": 51,
    "title": "Back to School Word Search",
    "category": "Classroom",
    "slug": "back-to-school-word-search",
    "difficulty": "easy",
    "audience": [
      "Kids",
      "classroom"
    ],
    "seed": "curated-back-to-school-word-search-v1",
    "words": [
      "SCHOOL",
      "TEACHER",
      "FRIENDS",
      "CLASS",
      "DESK",
      "BOOK",
      "PENCIL",
      "BACKPACK",
      "BUS",
      "LUNCH",
      "RECESS",
      "LEARN"
    ],
    "introduction": "Find words connected with returning to class, meeting teachers, organizing supplies, and starting a new school routine.",
    "context": "This printable is designed for the beginning of a school term without depending on a particular grade or curriculum.",
    "difficultyNote": "A twelve-word forward-only grid makes this suitable for a quick first-week activity.",
    "metaTitle": "Back to School Word Search | Easy Printable",
    "metaDescription": "Find school, teacher, friends, backpacks, books, recess, and more in this easy back-to-school word search with answers."
  },
  {
    "order": 52,
    "title": "Spelling Word Search",
    "category": "Classroom",
    "slug": "spelling-word-search",
    "difficulty": "medium",
    "audience": [
      "Classroom",
      "teachers"
    ],
    "seed": "curated-spelling-word-search-v1",
    "words": [
      "SPELLING",
      "LETTER",
      "SOUND",
      "SYLLABLE",
      "VOWEL",
      "CONSONANT",
      "WORD",
      "DICTIONARY",
      "PRACTICE",
      "PATTERN",
      "PREFIX",
      "SUFFIX",
      "ROOT",
      "MEANING",
      "SENTENCE",
      "CHECK"
    ],
    "introduction": "Search for terms used when studying spelling patterns, word parts, pronunciation, and written vocabulary.",
    "context": "The page works as a general spelling-vocabulary review and links naturally to the custom generator for weekly word lists.",
    "difficultyNote": "Longer language terms and reverse directions create a medium challenge.",
    "metaTitle": "Spelling Word Search | Printable Classroom Puzzle",
    "metaDescription": "Review vowels, consonants, syllables, prefixes, suffixes, and more with this printable spelling word search and key."
  },
  {
    "order": 53,
    "title": "Kindness Word Search",
    "category": "Values",
    "slug": "kindness-word-search",
    "difficulty": "easy",
    "audience": [
      "Classroom",
      "families"
    ],
    "seed": "curated-kindness-word-search-v1",
    "words": [
      "KINDNESS",
      "CARING",
      "HELP",
      "SHARE",
      "LISTEN",
      "INCLUDE",
      "RESPECT",
      "PATIENCE",
      "SUPPORT",
      "HONESTY",
      "SMILE",
      "THANKS"
    ],
    "introduction": "Find words describing considerate actions and respectful ways of treating other people.",
    "context": "The vocabulary can support a classroom or family discussion about practical behavior without presenting the puzzle as a social-emotional treatment.",
    "difficultyNote": "Forward directions make this an approachable values-themed activity.",
    "metaTitle": "Kindness Word Search | Free Printable Activity",
    "metaDescription": "Find caring, sharing, respect, patience, support, honesty, and more in this printable kindness word search with answers."
  },
  {
    "order": 54,
    "title": "Friendship Word Search",
    "category": "Values",
    "slug": "friendship-word-search",
    "difficulty": "easy",
    "audience": [
      "Classroom",
      "families"
    ],
    "seed": "curated-friendship-word-search-v1",
    "words": [
      "FRIEND",
      "TRUST",
      "SHARE",
      "LAUGH",
      "LISTEN",
      "SUPPORT",
      "HONEST",
      "CARING",
      "WELCOME",
      "TOGETHER",
      "RESPECT",
      "MEMORIES"
    ],
    "introduction": "Search for words connected with trust, listening, shared experiences, and respectful friendship.",
    "context": "The page provides a simple discussion starter or quiet activity without making claims about emotional or developmental outcomes.",
    "difficultyNote": "The twelve-word grid uses forward directions only.",
    "metaTitle": "Friendship Word Search | Easy Printable Puzzle",
    "metaDescription": "Find trust, sharing, laughter, support, respect, and more in this easy friendship word search with a printable answer key."
  },
  {
    "order": 55,
    "title": "Spring Word Search",
    "category": "Seasons and Holidays",
    "slug": "spring-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-spring-word-search-v1",
    "words": [
      "SPRING",
      "FLOWERS",
      "RAIN",
      "BLOSSOM",
      "GARDEN",
      "ROBIN",
      "BREEZE",
      "SUNSHINE",
      "SEEDS",
      "PUDDLES",
      "GREEN",
      "PICNIC"
    ],
    "introduction": "Find words connected with warmer weather, new plant growth, rain, and familiar spring activities.",
    "context": "The vocabulary remains seasonal and general, making the puzzle suitable for home or classroom use.",
    "difficultyNote": "Forward-only placement creates a quick seasonal puzzle.",
    "metaTitle": "Spring Word Search | Free Printable Seasonal Puzzle",
    "metaDescription": "Find flowers, rain, blossoms, gardens, sunshine, and more in this easy spring word search with a printable answer key."
  },
  {
    "order": 56,
    "title": "Summer Word Search",
    "category": "Seasons and Holidays",
    "slug": "summer-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-summer-word-search-v1",
    "words": [
      "SUMMER",
      "SUNSHINE",
      "BEACH",
      "PICNIC",
      "CAMPING",
      "SWIMMING",
      "SANDALS",
      "LEMONADE",
      "VACATION",
      "GARDEN",
      "SUNSET",
      "WATERMELON"
    ],
    "introduction": "Search for warm-weather activities, seasonal foods, travel, and outdoor summer vocabulary.",
    "context": "The puzzle uses broad summer themes rather than a particular event, destination, or commercial brand.",
    "difficultyNote": "Twelve forward-only words keep the puzzle easy to use.",
    "metaTitle": "Summer Word Search | Easy Free Printable",
    "metaDescription": "Find beaches, camping, swimming, lemonade, vacations, and more in this easy summer word search with answers."
  },
  {
    "order": 57,
    "title": "Fall Word Search",
    "category": "Seasons and Holidays",
    "slug": "fall-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "classroom"
    ],
    "seed": "curated-fall-word-search-v1",
    "words": [
      "AUTUMN",
      "LEAVES",
      "HARVEST",
      "APPLE",
      "PUMPKIN",
      "SWEATER",
      "ACORN",
      "CRISP",
      "ORANGE",
      "HAYRIDE",
      "CORN",
      "BREEZE"
    ],
    "introduction": "Find autumn words connected with changing leaves, harvest time, cooler weather, and seasonal foods.",
    "context": "The list gives the page a clear fall identity without depending on one holiday.",
    "difficultyNote": "Forward directions and twelve familiar terms create an easy puzzle.",
    "metaTitle": "Fall Word Search | Free Printable Autumn Puzzle",
    "metaDescription": "Find autumn leaves, pumpkins, apples, harvests, sweaters, and more in this easy fall word search with an answer key."
  },
  {
    "order": 58,
    "title": "Winter Word Search",
    "category": "Seasons and Holidays",
    "slug": "winter-word-search",
    "difficulty": "easy",
    "audience": [
      "General",
      "families"
    ],
    "seed": "curated-winter-word-search-v1",
    "words": [
      "WINTER",
      "SNOW",
      "FROST",
      "MITTENS",
      "SCARF",
      "SLED",
      "SKATES",
      "FIREPLACE",
      "COCOA",
      "ICICLE",
      "BOOTS",
      "BLANKET"
    ],
    "introduction": "Search for cold-weather clothing, snow activities, and familiar indoor winter comforts.",
    "context": "The puzzle remains a general winter activity and does not rely on a specific religious or commercial holiday.",
    "difficultyNote": "Forward-only paths keep the seasonal puzzle approachable.",
    "metaTitle": "Winter Word Search | Easy Printable Puzzle",
    "metaDescription": "Find snow, frost, mittens, sleds, skates, cocoa, and more in this easy winter word search with printable answers."
  },
  {
    "order": 59,
    "title": "Halloween Word Search",
    "category": "Seasons and Holidays",
    "slug": "halloween-word-search",
    "difficulty": "medium",
    "audience": [
      "Families",
      "classroom"
    ],
    "seed": "curated-halloween-word-search-v1",
    "words": [
      "HALLOWEEN",
      "PUMPKIN",
      "COSTUME",
      "CANDY",
      "GHOST",
      "WITCH",
      "BAT",
      "SPIDER",
      "SKELETON",
      "LANTERN",
      "MASK",
      "HAUNTED",
      "MOONLIGHT",
      "AUTUMN",
      "PARTY",
      "TREAT"
    ],
    "introduction": "Find familiar Halloween decorations, costumes, nighttime images, and party vocabulary.",
    "context": "The page uses generic seasonal words and avoids copyrighted characters, movies, and branded costumes.",
    "difficultyNote": "Sixteen words and reverse directions create a medium seasonal puzzle.",
    "metaTitle": "Halloween Word Search | Free Printable with Answers",
    "metaDescription": "Find pumpkins, costumes, ghosts, candy, bats, and more in this Halloween word search. Play online or print the PDF and key."
  },
  {
    "order": 60,
    "title": "Christmas Word Search",
    "category": "Seasons and Holidays",
    "slug": "christmas-word-search",
    "difficulty": "medium",
    "audience": [
      "Families",
      "classroom"
    ],
    "seed": "curated-christmas-word-search-v1",
    "words": [
      "CHRISTMAS",
      "TREE",
      "ORNAMENT",
      "LIGHTS",
      "CAROL",
      "STOCKING",
      "PRESENT",
      "WREATH",
      "CANDLE",
      "SLEIGH",
      "SNOWFLAKE",
      "HOLLY",
      "RIBBON",
      "BELLS",
      "FAMILY",
      "DINNER"
    ],
    "introduction": "Search for familiar Christmas decorations, music, gifts, gatherings, and seasonal symbols.",
    "context": "The vocabulary is generic and traditional, with no branded characters, movies, or commercial properties.",
    "difficultyNote": "Sixteen words and mixed directions create a medium puzzle.",
    "metaTitle": "Christmas Word Search | Free Printable Puzzle",
    "metaDescription": "Find trees, ornaments, lights, stockings, wreaths, bells, and more. Play or print this Christmas word search with answers."
  }
];

export interface CuratedTopic extends CuratedTopicSource {
  topicSlug: string;
  routeSlug: string;
  categorySegment: string;
  categorySlug: string;
  reviewedOn: string;
  rows: number;
  columns: number;
  relatedSlugs: string[];
  printNote: string;
}

const difficultySize: Record<Difficulty, number> = { easy: 12, medium: 15, hard: 18 };

export const curatedTopics: CuratedTopic[] = curatedTopicSource.map((topic, index, all) => {
  const category = categoryDetails[topic.category];
  const sameCategory = all.filter((candidate) => categoryDetails[candidate.category].segment === category.segment && candidate.slug !== topic.slug);
  const relatedSlugs = [
    ...sameCategory.slice(0, 5).map((candidate) => `${categoryDetails[candidate.category].segment}/${candidate.slug}`),
    ...all.filter((candidate) => categoryDetails[candidate.category].segment !== category.segment).slice(index % 10, index % 10 + 1).map((candidate) => `${categoryDetails[candidate.category].segment}/${candidate.slug}`)
  ].slice(0, 6);
  return {
    ...topic,
    topicSlug: topic.slug,
    routeSlug: `${category.segment}/${topic.slug}`,
    categorySegment: category.segment,
    categorySlug: category.slug,
    reviewedOn: CURATED_REVIEW_DATE,
    rows: difficultySize[topic.difficulty],
    columns: difficultySize[topic.difficulty],
    relatedSlugs,
    printNote: `The printable edition keeps ${topic.words[0]} and the other ${topic.words.length - 1} terms with this exact seeded grid; the PDF can include its matching solution page.`
  };
});

export const curatedTopicSlugs = new Set(curatedTopics.map((topic) => topic.routeSlug));

export function getCuratedTopic(categorySegment: string, topicSlug: string) {
  return curatedTopics.find((topic) => topic.categorySegment === categorySegment && topic.topicSlug === topicSlug);
}
